<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ACCHIGNLOIF</code>
 */
class ACCHIGNLOIF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OELNNDOBEKP AJMDFDMDMAN = 4;</code>
     */
    protected $AJMDFDMDMAN = 0;
    /**
     * Generated from protobuf field <code>bool EGPENEEKJMB = 12;</code>
     */
    protected $EGPENEEKJMB = false;
    /**
     * Generated from protobuf field <code>uint32 scene_event_id = 9;</code>
     */
    protected $scene_event_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $AJMDFDMDMAN
     *     @type bool $EGPENEEKJMB
     *     @type int $scene_event_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OELNNDOBEKP AJMDFDMDMAN = 4;</code>
     * @return int
     */
    public function getAJMDFDMDMAN()
    {
        return $this->AJMDFDMDMAN;
    }

    /**
     * Generated from protobuf field <code>.OELNNDOBEKP AJMDFDMDMAN = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAJMDFDMDMAN($var)
    {
        GPBUtil::checkEnum($var, \OELNNDOBEKP::class);
        $this->AJMDFDMDMAN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool EGPENEEKJMB = 12;</code>
     * @return bool
     */
    public function getEGPENEEKJMB()
    {
        return $this->EGPENEEKJMB;
    }

    /**
     * Generated from protobuf field <code>bool EGPENEEKJMB = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setEGPENEEKJMB($var)
    {
        GPBUtil::checkBool($var);
        $this->EGPENEEKJMB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 scene_event_id = 9;</code>
     * @return int
     */
    public function getSceneEventId()
    {
        return $this->scene_event_id;
    }

    /**
     * Generated from protobuf field <code>uint32 scene_event_id = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setSceneEventId($var)
    {
        GPBUtil::checkUint32($var);
        $this->scene_event_id = $var;

        return $this;
    }

}

