<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ACKEMBBHAPI</code>
 */
class ACKEMBBHAPI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ECPCKOPKCOA = 1;</code>
     */
    protected $ECPCKOPKCOA = 0;
    /**
     * Generated from protobuf field <code>double IAJHMELEJOB = 2;</code>
     */
    protected $IAJHMELEJOB = 0.0;
    /**
     * Generated from protobuf field <code>double OLPBENMDNJL = 3;</code>
     */
    protected $OLPBENMDNJL = 0.0;
    /**
     * Generated from protobuf field <code>uint32 BFEELFCPOCD = 4;</code>
     */
    protected $BFEELFCPOCD = 0;
    /**
     * Generated from protobuf field <code>uint32 DMMHEKOJLGC = 5;</code>
     */
    protected $DMMHEKOJLGC = 0;
    /**
     * Generated from protobuf field <code>uint32 LMCADMLONPL = 6;</code>
     */
    protected $LMCADMLONPL = 0;
    /**
     * Generated from protobuf field <code>uint32 HOBCDLDDBEE = 7;</code>
     */
    protected $HOBCDLDDBEE = 0;
    /**
     * Generated from protobuf field <code>double FMJPIKHPDJG = 8;</code>
     */
    protected $FMJPIKHPDJG = 0.0;
    /**
     * Generated from protobuf field <code>uint32 JLNENFKAFPH = 9;</code>
     */
    protected $JLNENFKAFPH = 0;
    /**
     * Generated from protobuf field <code>uint32 NMMMGHPEBNA = 10;</code>
     */
    protected $NMMMGHPEBNA = 0;
    /**
     * Generated from protobuf field <code>double NPMLANODKJM = 11;</code>
     */
    protected $NPMLANODKJM = 0.0;
    /**
     * Generated from protobuf field <code>uint32 DBFPHLOOAKG = 12;</code>
     */
    protected $DBFPHLOOAKG = 0;
    /**
     * Generated from protobuf field <code>uint32 EOEBMCFAEOL = 13;</code>
     */
    protected $EOEBMCFAEOL = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ECPCKOPKCOA
     *     @type float $IAJHMELEJOB
     *     @type float $OLPBENMDNJL
     *     @type int $BFEELFCPOCD
     *     @type int $DMMHEKOJLGC
     *     @type int $LMCADMLONPL
     *     @type int $HOBCDLDDBEE
     *     @type float $FMJPIKHPDJG
     *     @type int $JLNENFKAFPH
     *     @type int $NMMMGHPEBNA
     *     @type float $NPMLANODKJM
     *     @type int $DBFPHLOOAKG
     *     @type int $EOEBMCFAEOL
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ECPCKOPKCOA = 1;</code>
     * @return int
     */
    public function getECPCKOPKCOA()
    {
        return $this->ECPCKOPKCOA;
    }

    /**
     * Generated from protobuf field <code>uint32 ECPCKOPKCOA = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setECPCKOPKCOA($var)
    {
        GPBUtil::checkUint32($var);
        $this->ECPCKOPKCOA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double IAJHMELEJOB = 2;</code>
     * @return float
     */
    public function getIAJHMELEJOB()
    {
        return $this->IAJHMELEJOB;
    }

    /**
     * Generated from protobuf field <code>double IAJHMELEJOB = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setIAJHMELEJOB($var)
    {
        GPBUtil::checkDouble($var);
        $this->IAJHMELEJOB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double OLPBENMDNJL = 3;</code>
     * @return float
     */
    public function getOLPBENMDNJL()
    {
        return $this->OLPBENMDNJL;
    }

    /**
     * Generated from protobuf field <code>double OLPBENMDNJL = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setOLPBENMDNJL($var)
    {
        GPBUtil::checkDouble($var);
        $this->OLPBENMDNJL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 BFEELFCPOCD = 4;</code>
     * @return int
     */
    public function getBFEELFCPOCD()
    {
        return $this->BFEELFCPOCD;
    }

    /**
     * Generated from protobuf field <code>uint32 BFEELFCPOCD = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBFEELFCPOCD($var)
    {
        GPBUtil::checkUint32($var);
        $this->BFEELFCPOCD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 DMMHEKOJLGC = 5;</code>
     * @return int
     */
    public function getDMMHEKOJLGC()
    {
        return $this->DMMHEKOJLGC;
    }

    /**
     * Generated from protobuf field <code>uint32 DMMHEKOJLGC = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDMMHEKOJLGC($var)
    {
        GPBUtil::checkUint32($var);
        $this->DMMHEKOJLGC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 LMCADMLONPL = 6;</code>
     * @return int
     */
    public function getLMCADMLONPL()
    {
        return $this->LMCADMLONPL;
    }

    /**
     * Generated from protobuf field <code>uint32 LMCADMLONPL = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLMCADMLONPL($var)
    {
        GPBUtil::checkUint32($var);
        $this->LMCADMLONPL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 HOBCDLDDBEE = 7;</code>
     * @return int
     */
    public function getHOBCDLDDBEE()
    {
        return $this->HOBCDLDDBEE;
    }

    /**
     * Generated from protobuf field <code>uint32 HOBCDLDDBEE = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setHOBCDLDDBEE($var)
    {
        GPBUtil::checkUint32($var);
        $this->HOBCDLDDBEE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double FMJPIKHPDJG = 8;</code>
     * @return float
     */
    public function getFMJPIKHPDJG()
    {
        return $this->FMJPIKHPDJG;
    }

    /**
     * Generated from protobuf field <code>double FMJPIKHPDJG = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setFMJPIKHPDJG($var)
    {
        GPBUtil::checkDouble($var);
        $this->FMJPIKHPDJG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 JLNENFKAFPH = 9;</code>
     * @return int
     */
    public function getJLNENFKAFPH()
    {
        return $this->JLNENFKAFPH;
    }

    /**
     * Generated from protobuf field <code>uint32 JLNENFKAFPH = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setJLNENFKAFPH($var)
    {
        GPBUtil::checkUint32($var);
        $this->JLNENFKAFPH = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 NMMMGHPEBNA = 10;</code>
     * @return int
     */
    public function getNMMMGHPEBNA()
    {
        return $this->NMMMGHPEBNA;
    }

    /**
     * Generated from protobuf field <code>uint32 NMMMGHPEBNA = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setNMMMGHPEBNA($var)
    {
        GPBUtil::checkUint32($var);
        $this->NMMMGHPEBNA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double NPMLANODKJM = 11;</code>
     * @return float
     */
    public function getNPMLANODKJM()
    {
        return $this->NPMLANODKJM;
    }

    /**
     * Generated from protobuf field <code>double NPMLANODKJM = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setNPMLANODKJM($var)
    {
        GPBUtil::checkDouble($var);
        $this->NPMLANODKJM = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 DBFPHLOOAKG = 12;</code>
     * @return int
     */
    public function getDBFPHLOOAKG()
    {
        return $this->DBFPHLOOAKG;
    }

    /**
     * Generated from protobuf field <code>uint32 DBFPHLOOAKG = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDBFPHLOOAKG($var)
    {
        GPBUtil::checkUint32($var);
        $this->DBFPHLOOAKG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 EOEBMCFAEOL = 13;</code>
     * @return int
     */
    public function getEOEBMCFAEOL()
    {
        return $this->EOEBMCFAEOL;
    }

    /**
     * Generated from protobuf field <code>uint32 EOEBMCFAEOL = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setEOEBMCFAEOL($var)
    {
        GPBUtil::checkUint32($var);
        $this->EOEBMCFAEOL = $var;

        return $this;
    }

}

