<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AFBGDOPLIPP</code>
 */
class AFBGDOPLIPP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .NACIBCFJGKF abcjiognklj = 1;</code>
     */
    private $abcjiognklj;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\NACIBCFJGKF>|\Google\Protobuf\Internal\RepeatedField $abcjiognklj
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .NACIBCFJGKF abcjiognklj = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAbcjiognklj()
    {
        return $this->abcjiognklj;
    }

    /**
     * Generated from protobuf field <code>repeated .NACIBCFJGKF abcjiognklj = 1;</code>
     * @param array<\NACIBCFJGKF>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAbcjiognklj($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \NACIBCFJGKF::class);
        $this->abcjiognklj = $arr;

        return $this;
    }

}

