<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AGBKCIIINEL</code>
 */
class AGBKCIIINEL extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RelicAffix sub_affix_list = 3;</code>
     */
    private $sub_affix_list;
    /**
     * Generated from protobuf field <code>uint32 EBGJHJLICDI = 1;</code>
     */
    protected $EBGJHJLICDI = 0;
    /**
     * Generated from protobuf field <code>uint32 exp = 4;</code>
     */
    protected $exp = 0;
    /**
     * Generated from protobuf field <code>uint32 main_affix_id = 14;</code>
     */
    protected $main_affix_id = 0;
    /**
     * Generated from protobuf field <code>uint32 level = 13;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\RelicAffix>|\Google\Protobuf\Internal\RepeatedField $sub_affix_list
     *     @type int $EBGJHJLICDI
     *     @type int $exp
     *     @type int $main_affix_id
     *     @type int $level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RelicAffix sub_affix_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubAffixList()
    {
        return $this->sub_affix_list;
    }

    /**
     * Generated from protobuf field <code>repeated .RelicAffix sub_affix_list = 3;</code>
     * @param array<\RelicAffix>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubAffixList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RelicAffix::class);
        $this->sub_affix_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 EBGJHJLICDI = 1;</code>
     * @return int
     */
    public function getEBGJHJLICDI()
    {
        return $this->EBGJHJLICDI;
    }

    /**
     * Generated from protobuf field <code>uint32 EBGJHJLICDI = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEBGJHJLICDI($var)
    {
        GPBUtil::checkUint32($var);
        $this->EBGJHJLICDI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 4;</code>
     * @return int
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkUint32($var);
        $this->exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 main_affix_id = 14;</code>
     * @return int
     */
    public function getMainAffixId()
    {
        return $this->main_affix_id;
    }

    /**
     * Generated from protobuf field <code>uint32 main_affix_id = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setMainAffixId($var)
    {
        GPBUtil::checkUint32($var);
        $this->main_affix_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 13;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

}

