<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AMBNFELJDMK</code>
 */
class AMBNFELJDMK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 IJIIPGAFKJN = 7;</code>
     */
    protected $IJIIPGAFKJN = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $IJIIPGAFKJN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 IJIIPGAFKJN = 7;</code>
     * @return int
     */
    public function getIJIIPGAFKJN()
    {
        return $this->IJIIPGAFKJN;
    }

    /**
     * Generated from protobuf field <code>uint32 IJIIPGAFKJN = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setIJIIPGAFKJN($var)
    {
        GPBUtil::checkUint32($var);
        $this->IJIIPGAFKJN = $var;

        return $this;
    }

}

