<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ANFCFBONBEM</code>
 */
class ANFCFBONBEM extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 bijlejffmim = 14;</code>
     */
    protected $bijlejffmim = 0;
    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>uint32 monster_id = 5;</code>
     */
    protected $monster_id = 0;
    /**
     * Generated from protobuf field <code>bool jcnedegkkja = 11;</code>
     */
    protected $jcnedegkkja = false;
    /**
     * Generated from protobuf field <code>uint32 world_level = 10;</code>
     */
    protected $world_level = 0;
    /**
     * Generated from protobuf field <code>uint32 config_id = 2;</code>
     */
    protected $config_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $bijlejffmim
     *     @type int|string $create_time
     *     @type int $monster_id
     *     @type bool $jcnedegkkja
     *     @type int $world_level
     *     @type int $config_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 bijlejffmim = 14;</code>
     * @return int
     */
    public function getBijlejffmim()
    {
        return $this->bijlejffmim;
    }

    /**
     * Generated from protobuf field <code>uint32 bijlejffmim = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setBijlejffmim($var)
    {
        GPBUtil::checkUint32($var);
        $this->bijlejffmim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 monster_id = 5;</code>
     * @return int
     */
    public function getMonsterId()
    {
        return $this->monster_id;
    }

    /**
     * Generated from protobuf field <code>uint32 monster_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMonsterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->monster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool jcnedegkkja = 11;</code>
     * @return bool
     */
    public function getJcnedegkkja()
    {
        return $this->jcnedegkkja;
    }

    /**
     * Generated from protobuf field <code>bool jcnedegkkja = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setJcnedegkkja($var)
    {
        GPBUtil::checkBool($var);
        $this->jcnedegkkja = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 10;</code>
     * @return int
     */
    public function getWorldLevel()
    {
        return $this->world_level;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setWorldLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->world_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 config_id = 2;</code>
     * @return int
     */
    public function getConfigId()
    {
        return $this->config_id;
    }

    /**
     * Generated from protobuf field <code>uint32 config_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConfigId($var)
    {
        GPBUtil::checkUint32($var);
        $this->config_id = $var;

        return $this;
    }

}

