<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

/**
 * Protobuf type <code>AvatarType</code>
 */
class AvatarType
{
    /**
     * Generated from protobuf enum <code>AVATAR_TYPE_NONE = 0;</code>
     */
    const AVATAR_TYPE_NONE = 0;
    /**
     * Generated from protobuf enum <code>AVATAR_TRIAL_TYPE = 1;</code>
     */
    const AVATAR_TRIAL_TYPE = 1;
    /**
     * Generated from protobuf enum <code>AVATAR_LIMIT_TYPE = 2;</code>
     */
    const AVATAR_LIMIT_TYPE = 2;
    /**
     * Generated from protobuf enum <code>AVATAR_FORMAL_TYPE = 3;</code>
     */
    const AVATAR_FORMAL_TYPE = 3;
    /**
     * Generated from protobuf enum <code>AVATAR_ASSIST_TYPE = 4;</code>
     */
    const AVATAR_ASSIST_TYPE = 4;
    /**
     * Generated from protobuf enum <code>AVATAR_AETHER_DIVIDE_TYPE = 5;</code>
     */
    const AVATAR_AETHER_DIVIDE_TYPE = 5;
    /**
     * Generated from protobuf enum <code>AVATAR_UPGRADE_AVAILABLE_TYPE = 6;</code>
     */
    const AVATAR_UPGRADE_AVAILABLE_TYPE = 6;

    private static $valueToName = [
        self::AVATAR_TYPE_NONE => 'AVATAR_TYPE_NONE',
        self::AVATAR_TRIAL_TYPE => 'AVATAR_TRIAL_TYPE',
        self::AVATAR_LIMIT_TYPE => 'AVATAR_LIMIT_TYPE',
        self::AVATAR_FORMAL_TYPE => 'AVATAR_FORMAL_TYPE',
        self::AVATAR_ASSIST_TYPE => 'AVATAR_ASSIST_TYPE',
        self::AVATAR_AETHER_DIVIDE_TYPE => 'AVATAR_AETHER_DIVIDE_TYPE',
        self::AVATAR_UPGRADE_AVAILABLE_TYPE => 'AVATAR_UPGRADE_AVAILABLE_TYPE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

