<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BAOPAGENGEI</code>
 */
class BAOPAGENGEI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 GMOJJNBEIFL = 14;</code>
     */
    protected $GMOJJNBEIFL = 0;
    /**
     * Generated from protobuf field <code>bool LNFDEFNJOKJ = 5;</code>
     */
    protected $LNFDEFNJOKJ = false;
    /**
     * Generated from protobuf field <code>repeated uint32 GIBEGFHBEFD = 8;</code>
     */
    private $GIBEGFHBEFD;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $GMOJJNBEIFL
     *     @type bool $LNFDEFNJOKJ
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $GIBEGFHBEFD
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 GMOJJNBEIFL = 14;</code>
     * @return int
     */
    public function getGMOJJNBEIFL()
    {
        return $this->GMOJJNBEIFL;
    }

    /**
     * Generated from protobuf field <code>uint32 GMOJJNBEIFL = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setGMOJJNBEIFL($var)
    {
        GPBUtil::checkUint32($var);
        $this->GMOJJNBEIFL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool LNFDEFNJOKJ = 5;</code>
     * @return bool
     */
    public function getLNFDEFNJOKJ()
    {
        return $this->LNFDEFNJOKJ;
    }

    /**
     * Generated from protobuf field <code>bool LNFDEFNJOKJ = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setLNFDEFNJOKJ($var)
    {
        GPBUtil::checkBool($var);
        $this->LNFDEFNJOKJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 GIBEGFHBEFD = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGIBEGFHBEFD()
    {
        return $this->GIBEGFHBEFD;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 GIBEGFHBEFD = 8;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGIBEGFHBEFD($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->GIBEGFHBEFD = $arr;

        return $this;
    }

}

