<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BBKMOPPLBEP</code>
 */
class BBKMOPPLBEP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 mmeieogmoeg = 5;</code>
     */
    private $mmeieogmoeg;
    /**
     * Generated from protobuf field <code>uint32 select_hint_id = 1;</code>
     */
    protected $select_hint_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $mmeieogmoeg
     *     @type int $select_hint_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 mmeieogmoeg = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMmeieogmoeg()
    {
        return $this->mmeieogmoeg;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 mmeieogmoeg = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMmeieogmoeg($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->mmeieogmoeg = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 select_hint_id = 1;</code>
     * @return int
     */
    public function getSelectHintId()
    {
        return $this->select_hint_id;
    }

    /**
     * Generated from protobuf field <code>uint32 select_hint_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSelectHintId($var)
    {
        GPBUtil::checkUint32($var);
        $this->select_hint_id = $var;

        return $this;
    }

}

