<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BJNNBGFLMGF</code>
 */
class BJNNBGFLMGF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string PGBCFLGAICO = 4;</code>
     */
    protected $PGBCFLGAICO = '';
    /**
     * Generated from protobuf field <code>uint32 IEGNKPNHBIA = 3;</code>
     */
    protected $IEGNKPNHBIA = 0;
    /**
     * Generated from protobuf field <code>uint32 NDHMLKCMOMJ = 8;</code>
     */
    protected $NDHMLKCMOMJ = 0;
    /**
     * Generated from protobuf field <code>.ProductGiftType CNODGPHDGOE = 9;</code>
     */
    protected $CNODGPHDGOE = 0;
    /**
     * Generated from protobuf field <code>bool DGPKAFCLJJD = 7;</code>
     */
    protected $DGPKAFCLJJD = false;
    /**
     * Generated from protobuf field <code>string INMDPFMPFMK = 6;</code>
     */
    protected $INMDPFMPFMK = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $PGBCFLGAICO
     *     @type int $IEGNKPNHBIA
     *     @type int $NDHMLKCMOMJ
     *     @type int $CNODGPHDGOE
     *     @type bool $DGPKAFCLJJD
     *     @type string $INMDPFMPFMK
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string PGBCFLGAICO = 4;</code>
     * @return string
     */
    public function getPGBCFLGAICO()
    {
        return $this->PGBCFLGAICO;
    }

    /**
     * Generated from protobuf field <code>string PGBCFLGAICO = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPGBCFLGAICO($var)
    {
        GPBUtil::checkString($var, True);
        $this->PGBCFLGAICO = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 IEGNKPNHBIA = 3;</code>
     * @return int
     */
    public function getIEGNKPNHBIA()
    {
        return $this->IEGNKPNHBIA;
    }

    /**
     * Generated from protobuf field <code>uint32 IEGNKPNHBIA = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIEGNKPNHBIA($var)
    {
        GPBUtil::checkUint32($var);
        $this->IEGNKPNHBIA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 NDHMLKCMOMJ = 8;</code>
     * @return int
     */
    public function getNDHMLKCMOMJ()
    {
        return $this->NDHMLKCMOMJ;
    }

    /**
     * Generated from protobuf field <code>uint32 NDHMLKCMOMJ = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setNDHMLKCMOMJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->NDHMLKCMOMJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ProductGiftType CNODGPHDGOE = 9;</code>
     * @return int
     */
    public function getCNODGPHDGOE()
    {
        return $this->CNODGPHDGOE;
    }

    /**
     * Generated from protobuf field <code>.ProductGiftType CNODGPHDGOE = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCNODGPHDGOE($var)
    {
        GPBUtil::checkEnum($var, \ProductGiftType::class);
        $this->CNODGPHDGOE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DGPKAFCLJJD = 7;</code>
     * @return bool
     */
    public function getDGPKAFCLJJD()
    {
        return $this->DGPKAFCLJJD;
    }

    /**
     * Generated from protobuf field <code>bool DGPKAFCLJJD = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setDGPKAFCLJJD($var)
    {
        GPBUtil::checkBool($var);
        $this->DGPKAFCLJJD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string INMDPFMPFMK = 6;</code>
     * @return string
     */
    public function getINMDPFMPFMK()
    {
        return $this->INMDPFMPFMK;
    }

    /**
     * Generated from protobuf field <code>string INMDPFMPFMK = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setINMDPFMPFMK($var)
    {
        GPBUtil::checkString($var, True);
        $this->INMDPFMPFMK = $var;

        return $this;
    }

}

