<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BKBKILCCNGC</code>
 */
class BKBKILCCNGC extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OOKFHBFLPEB jialocpokfj = 15;</code>
     */
    protected $jialocpokfj = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OOKFHBFLPEB $jialocpokfj
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OOKFHBFLPEB jialocpokfj = 15;</code>
     * @return \OOKFHBFLPEB|null
     */
    public function getJialocpokfj()
    {
        return $this->jialocpokfj;
    }

    public function hasJialocpokfj()
    {
        return isset($this->jialocpokfj);
    }

    public function clearJialocpokfj()
    {
        unset($this->jialocpokfj);
    }

    /**
     * Generated from protobuf field <code>.OOKFHBFLPEB jialocpokfj = 15;</code>
     * @param \OOKFHBFLPEB $var
     * @return $this
     */
    public function setJialocpokfj($var)
    {
        GPBUtil::checkMessage($var, \OOKFHBFLPEB::class);
        $this->jialocpokfj = $var;

        return $this;
    }

}

