<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CAEPOCNBJKF</code>
 */
class CAEPOCNBJKF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 opalijhhpie = 8;</code>
     */
    protected $opalijhhpie = 0;
    /**
     * Generated from protobuf field <code>uint32 njmhcjgeogi = 15;</code>
     */
    protected $njmhcjgeogi = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $opalijhhpie
     *     @type int $njmhcjgeogi
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 opalijhhpie = 8;</code>
     * @return int
     */
    public function getOpalijhhpie()
    {
        return $this->opalijhhpie;
    }

    /**
     * Generated from protobuf field <code>uint32 opalijhhpie = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setOpalijhhpie($var)
    {
        GPBUtil::checkUint32($var);
        $this->opalijhhpie = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 njmhcjgeogi = 15;</code>
     * @return int
     */
    public function getNjmhcjgeogi()
    {
        return $this->njmhcjgeogi;
    }

    /**
     * Generated from protobuf field <code>uint32 njmhcjgeogi = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setNjmhcjgeogi($var)
    {
        GPBUtil::checkUint32($var);
        $this->njmhcjgeogi = $var;

        return $this;
    }

}

