<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PLJLHPHCIDI (5469)
 *
 * Generated from protobuf message <code>ChessRogueUpdateLevelBaseInfoScNotify</code>
 */
class ChessRogueUpdateLevelBaseInfoScNotify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ANEHJMAFBLJ reason = 15;</code>
     */
    protected $reason = 0;
    /**
     * Generated from protobuf field <code>.LMIBFMLFCGO gcceggbeicj = 12;</code>
     */
    protected $gcceggbeicj = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $reason
     *     @type int $gcceggbeicj
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ANEHJMAFBLJ reason = 15;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>.ANEHJMAFBLJ reason = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \ANEHJMAFBLJ::class);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LMIBFMLFCGO gcceggbeicj = 12;</code>
     * @return int
     */
    public function getGcceggbeicj()
    {
        return $this->gcceggbeicj;
    }

    /**
     * Generated from protobuf field <code>.LMIBFMLFCGO gcceggbeicj = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setGcceggbeicj($var)
    {
        GPBUtil::checkEnum($var, \LMIBFMLFCGO::class);
        $this->gcceggbeicj = $var;

        return $this;
    }

}

