<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DPJLIBDPFOF (5539)
 *
 * Generated from protobuf message <code>ChessRogueQuestFinishNotify</code>
 */
class ChessRogueQuestFinishNotify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 hcopmgfadoo = 5;</code>
     */
    protected $hcopmgfadoo = 0;
    /**
     * Generated from protobuf field <code>uint32 quest_id = 3;</code>
     */
    protected $quest_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $hcopmgfadoo
     *     @type int $quest_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 hcopmgfadoo = 5;</code>
     * @return int
     */
    public function getHcopmgfadoo()
    {
        return $this->hcopmgfadoo;
    }

    /**
     * Generated from protobuf field <code>uint32 hcopmgfadoo = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setHcopmgfadoo($var)
    {
        GPBUtil::checkUint32($var);
        $this->hcopmgfadoo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 quest_id = 3;</code>
     * @return int
     */
    public function getQuestId()
    {
        return $this->quest_id;
    }

    /**
     * Generated from protobuf field <code>uint32 quest_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setQuestId($var)
    {
        GPBUtil::checkUint32($var);
        $this->quest_id = $var;

        return $this;
    }

}

