<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

/**
 * NMGLEBDEAEM
 *
 * Protobuf type <code>CmdServerPrefsType</code>
 */
class CmdServerPrefsType
{
    /**
     * Generated from protobuf enum <code>CmdServerPrefsTypeNone = 0;</code>
     */
    const CmdServerPrefsTypeNone = 0;
    /**
     * Generated from protobuf enum <code>CmdGetAllServerPrefsDataCsReq = 6136;</code>
     */
    const CmdGetAllServerPrefsDataCsReq = 6136;
    /**
     * Generated from protobuf enum <code>CmdGetAllServerPrefsDataScRsp = 6195;</code>
     */
    const CmdGetAllServerPrefsDataScRsp = 6195;
    /**
     * Generated from protobuf enum <code>CmdGetServerPrefsDataScRsp = 6127;</code>
     */
    const CmdGetServerPrefsDataScRsp = 6127;
    /**
     * Generated from protobuf enum <code>CmdUpdateServerPrefsDataCsReq = 6167;</code>
     */
    const CmdUpdateServerPrefsDataCsReq = 6167;
    /**
     * Generated from protobuf enum <code>CmdUpdateServerPrefsDataScRsp = 6128;</code>
     */
    const CmdUpdateServerPrefsDataScRsp = 6128;
    /**
     * Generated from protobuf enum <code>CmdGetServerPrefsDataCsReq = 6184;</code>
     */
    const CmdGetServerPrefsDataCsReq = 6184;

    private static $valueToName = [
        self::CmdServerPrefsTypeNone => 'CmdServerPrefsTypeNone',
        self::CmdGetAllServerPrefsDataCsReq => 'CmdGetAllServerPrefsDataCsReq',
        self::CmdGetAllServerPrefsDataScRsp => 'CmdGetAllServerPrefsDataScRsp',
        self::CmdGetServerPrefsDataScRsp => 'CmdGetServerPrefsDataScRsp',
        self::CmdUpdateServerPrefsDataCsReq => 'CmdUpdateServerPrefsDataCsReq',
        self::CmdUpdateServerPrefsDataScRsp => 'CmdUpdateServerPrefsDataScRsp',
        self::CmdGetServerPrefsDataCsReq => 'CmdGetServerPrefsDataCsReq',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

