<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CNEGKPBIFCA</code>
 */
class CNEGKPBIFCA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 HJHAIHFEFEN = 11;</code>
     */
    protected $HJHAIHFEFEN = 0;
    /**
     * Generated from protobuf field <code>.EPMEDGJKJOB status = 8;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 OHLACBFPACN = 14;</code>
     */
    protected $OHLACBFPACN = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $HJHAIHFEFEN
     *     @type int $status
     *     @type int $OHLACBFPACN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 HJHAIHFEFEN = 11;</code>
     * @return int
     */
    public function getHJHAIHFEFEN()
    {
        return $this->HJHAIHFEFEN;
    }

    /**
     * Generated from protobuf field <code>uint32 HJHAIHFEFEN = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setHJHAIHFEFEN($var)
    {
        GPBUtil::checkUint32($var);
        $this->HJHAIHFEFEN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.EPMEDGJKJOB status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.EPMEDGJKJOB status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \EPMEDGJKJOB::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 OHLACBFPACN = 14;</code>
     * @return int
     */
    public function getOHLACBFPACN()
    {
        return $this->OHLACBFPACN;
    }

    /**
     * Generated from protobuf field <code>uint32 OHLACBFPACN = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setOHLACBFPACN($var)
    {
        GPBUtil::checkUint32($var);
        $this->OHLACBFPACN = $var;

        return $this;
    }

}

