<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DBAMJHDCECF</code>
 */
class DBAMJHDCECF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 4;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.LMKFPPPCHCI LCKJCKJBLEC = 2;</code>
     */
    protected $LCKJCKJBLEC = null;
    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 10;</code>
     */
    protected $NMJLDCHMDPE = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type \LMKFPPPCHCI $LCKJCKJBLEC
     *     @type \NEKEEJIKGKJ $NMJLDCHMDPE
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 4;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LMKFPPPCHCI LCKJCKJBLEC = 2;</code>
     * @return \LMKFPPPCHCI|null
     */
    public function getLCKJCKJBLEC()
    {
        return $this->LCKJCKJBLEC;
    }

    public function hasLCKJCKJBLEC()
    {
        return isset($this->LCKJCKJBLEC);
    }

    public function clearLCKJCKJBLEC()
    {
        unset($this->LCKJCKJBLEC);
    }

    /**
     * Generated from protobuf field <code>.LMKFPPPCHCI LCKJCKJBLEC = 2;</code>
     * @param \LMKFPPPCHCI $var
     * @return $this
     */
    public function setLCKJCKJBLEC($var)
    {
        GPBUtil::checkMessage($var, \LMKFPPPCHCI::class);
        $this->LCKJCKJBLEC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 10;</code>
     * @return \NEKEEJIKGKJ|null
     */
    public function getNMJLDCHMDPE()
    {
        return $this->NMJLDCHMDPE;
    }

    public function hasNMJLDCHMDPE()
    {
        return isset($this->NMJLDCHMDPE);
    }

    public function clearNMJLDCHMDPE()
    {
        unset($this->NMJLDCHMDPE);
    }

    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 10;</code>
     * @param \NEKEEJIKGKJ $var
     * @return $this
     */
    public function setNMJLDCHMDPE($var)
    {
        GPBUtil::checkMessage($var, \NEKEEJIKGKJ::class);
        $this->NMJLDCHMDPE = $var;

        return $this;
    }

}

