<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LJICHHELNOI (2946)
 *
 * Generated from protobuf message <code>DeleteFriendCsReq</code>
 */
class DeleteFriendCsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 icgghnnhbec = 7;</code>
     */
    protected $icgghnnhbec = 0;
    /**
     * Generated from protobuf field <code>uint32 uid = 12;</code>
     */
    protected $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $icgghnnhbec
     *     @type int $uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 icgghnnhbec = 7;</code>
     * @return int
     */
    public function getIcgghnnhbec()
    {
        return $this->icgghnnhbec;
    }

    /**
     * Generated from protobuf field <code>uint32 icgghnnhbec = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setIcgghnnhbec($var)
    {
        GPBUtil::checkUint32($var);
        $this->icgghnnhbec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 12;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

}

