<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DJNNNGFNMPJ</code>
 */
class DJNNNGFNMPJ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.LCCEPOAOLKK CFBHGFCNJAM = 1;</code>
     */
    protected $CFBHGFCNJAM = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LCCEPOAOLKK $CFBHGFCNJAM
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.LCCEPOAOLKK CFBHGFCNJAM = 1;</code>
     * @return \LCCEPOAOLKK|null
     */
    public function getCFBHGFCNJAM()
    {
        return $this->CFBHGFCNJAM;
    }

    public function hasCFBHGFCNJAM()
    {
        return isset($this->CFBHGFCNJAM);
    }

    public function clearCFBHGFCNJAM()
    {
        unset($this->CFBHGFCNJAM);
    }

    /**
     * Generated from protobuf field <code>.LCCEPOAOLKK CFBHGFCNJAM = 1;</code>
     * @param \LCCEPOAOLKK $var
     * @return $this
     */
    public function setCFBHGFCNJAM($var)
    {
        GPBUtil::checkMessage($var, \LCCEPOAOLKK::class);
        $this->CFBHGFCNJAM = $var;

        return $this;
    }

}

