<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DKOCAAOHIBK</code>
 */
class DKOCAAOHIBK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 pddfkaelhmp = 13;</code>
     */
    protected $pddfkaelhmp = 0;
    /**
     * Generated from protobuf field <code>uint32 challenge_id = 1;</code>
     */
    protected $challenge_id = 0;
    /**
     * Generated from protobuf field <code>uint32 biidjgdiejd = 12;</code>
     */
    protected $biidjgdiejd = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 avatar_list = 9;</code>
     */
    private $avatar_list;
    /**
     * Generated from protobuf field <code>uint32 fehjibildmm = 15;</code>
     */
    protected $fehjibildmm = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 gkfibaeohem = 7;</code>
     */
    private $gkfibaeohem;
    /**
     * Generated from protobuf field <code>bool niodmidciim = 8;</code>
     */
    protected $niodmidciim = false;
    /**
     * Generated from protobuf field <code>uint32 ifefgdnfkno = 5;</code>
     */
    protected $ifefgdnfkno = 0;
    /**
     * Generated from protobuf field <code>uint32 fjdmbjkdcki = 4;</code>
     */
    protected $fjdmbjkdcki = 0;
    /**
     * Generated from protobuf field <code>repeated .PAHLIMCJBEB liiamdgkpaf = 6;</code>
     */
    private $liiamdgkpaf;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pddfkaelhmp
     *     @type int $challenge_id
     *     @type int $biidjgdiejd
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $avatar_list
     *     @type int $fehjibildmm
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $gkfibaeohem
     *     @type bool $niodmidciim
     *     @type int $ifefgdnfkno
     *     @type int $fjdmbjkdcki
     *     @type array<\PAHLIMCJBEB>|\Google\Protobuf\Internal\RepeatedField $liiamdgkpaf
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 pddfkaelhmp = 13;</code>
     * @return int
     */
    public function getPddfkaelhmp()
    {
        return $this->pddfkaelhmp;
    }

    /**
     * Generated from protobuf field <code>uint32 pddfkaelhmp = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setPddfkaelhmp($var)
    {
        GPBUtil::checkUint32($var);
        $this->pddfkaelhmp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 challenge_id = 1;</code>
     * @return int
     */
    public function getChallengeId()
    {
        return $this->challenge_id;
    }

    /**
     * Generated from protobuf field <code>uint32 challenge_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setChallengeId($var)
    {
        GPBUtil::checkUint32($var);
        $this->challenge_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 biidjgdiejd = 12;</code>
     * @return int
     */
    public function getBiidjgdiejd()
    {
        return $this->biidjgdiejd;
    }

    /**
     * Generated from protobuf field <code>uint32 biidjgdiejd = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setBiidjgdiejd($var)
    {
        GPBUtil::checkUint32($var);
        $this->biidjgdiejd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 avatar_list = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvatarList()
    {
        return $this->avatar_list;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 avatar_list = 9;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvatarList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->avatar_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 fehjibildmm = 15;</code>
     * @return int
     */
    public function getFehjibildmm()
    {
        return $this->fehjibildmm;
    }

    /**
     * Generated from protobuf field <code>uint32 fehjibildmm = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setFehjibildmm($var)
    {
        GPBUtil::checkUint32($var);
        $this->fehjibildmm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 gkfibaeohem = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGkfibaeohem()
    {
        return $this->gkfibaeohem;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 gkfibaeohem = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGkfibaeohem($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->gkfibaeohem = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool niodmidciim = 8;</code>
     * @return bool
     */
    public function getNiodmidciim()
    {
        return $this->niodmidciim;
    }

    /**
     * Generated from protobuf field <code>bool niodmidciim = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setNiodmidciim($var)
    {
        GPBUtil::checkBool($var);
        $this->niodmidciim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ifefgdnfkno = 5;</code>
     * @return int
     */
    public function getIfefgdnfkno()
    {
        return $this->ifefgdnfkno;
    }

    /**
     * Generated from protobuf field <code>uint32 ifefgdnfkno = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIfefgdnfkno($var)
    {
        GPBUtil::checkUint32($var);
        $this->ifefgdnfkno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 fjdmbjkdcki = 4;</code>
     * @return int
     */
    public function getFjdmbjkdcki()
    {
        return $this->fjdmbjkdcki;
    }

    /**
     * Generated from protobuf field <code>uint32 fjdmbjkdcki = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFjdmbjkdcki($var)
    {
        GPBUtil::checkUint32($var);
        $this->fjdmbjkdcki = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PAHLIMCJBEB liiamdgkpaf = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLiiamdgkpaf()
    {
        return $this->liiamdgkpaf;
    }

    /**
     * Generated from protobuf field <code>repeated .PAHLIMCJBEB liiamdgkpaf = 6;</code>
     * @param array<\PAHLIMCJBEB>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLiiamdgkpaf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PAHLIMCJBEB::class);
        $this->liiamdgkpaf = $arr;

        return $this;
    }

}

