<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DNGHNGAEFNF</code>
 */
class DNGHNGAEFNF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.NBOICPBANIC LKGOAPJDNBJ = 2;</code>
     */
    protected $LKGOAPJDNBJ = null;
    /**
     * Generated from protobuf field <code>.BNKNFJKMJIE BCBJPFIKPHG = 12;</code>
     */
    protected $BCBJPFIKPHG = null;
    /**
     * Generated from protobuf field <code>.LMPHODOEHCN APLCCKHHPKC = 1;</code>
     */
    protected $APLCCKHHPKC = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 14;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.IFNCHAPEMHD PPAEOCBACHN = 15;</code>
     */
    protected $PPAEOCBACHN = null;
    /**
     * Generated from protobuf field <code>.JGNAJFOGFBJ DBBDJBPBJPA = 8;</code>
     */
    protected $DBBDJBPBJPA = null;
    /**
     * Generated from protobuf field <code>.FBGHJICBPMN BDAJBMAANIN = 11;</code>
     */
    protected $BDAJBMAANIN = null;
    /**
     * Generated from protobuf field <code>.AGFNMLEBEJD KACLLKAKKKO = 13;</code>
     */
    protected $KACLLKAKKKO = null;
    /**
     * Generated from protobuf field <code>.APKPMOHIBKJ JOCEJHGHLEM = 9;</code>
     */
    protected $JOCEJHGHLEM = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NBOICPBANIC $LKGOAPJDNBJ
     *     @type \BNKNFJKMJIE $BCBJPFIKPHG
     *     @type \LMPHODOEHCN $APLCCKHHPKC
     *     @type int $retcode
     *     @type \IFNCHAPEMHD $PPAEOCBACHN
     *     @type \JGNAJFOGFBJ $DBBDJBPBJPA
     *     @type \FBGHJICBPMN $BDAJBMAANIN
     *     @type \AGFNMLEBEJD $KACLLKAKKKO
     *     @type \APKPMOHIBKJ $JOCEJHGHLEM
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.NBOICPBANIC LKGOAPJDNBJ = 2;</code>
     * @return \NBOICPBANIC|null
     */
    public function getLKGOAPJDNBJ()
    {
        return $this->LKGOAPJDNBJ;
    }

    public function hasLKGOAPJDNBJ()
    {
        return isset($this->LKGOAPJDNBJ);
    }

    public function clearLKGOAPJDNBJ()
    {
        unset($this->LKGOAPJDNBJ);
    }

    /**
     * Generated from protobuf field <code>.NBOICPBANIC LKGOAPJDNBJ = 2;</code>
     * @param \NBOICPBANIC $var
     * @return $this
     */
    public function setLKGOAPJDNBJ($var)
    {
        GPBUtil::checkMessage($var, \NBOICPBANIC::class);
        $this->LKGOAPJDNBJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.BNKNFJKMJIE BCBJPFIKPHG = 12;</code>
     * @return \BNKNFJKMJIE|null
     */
    public function getBCBJPFIKPHG()
    {
        return $this->BCBJPFIKPHG;
    }

    public function hasBCBJPFIKPHG()
    {
        return isset($this->BCBJPFIKPHG);
    }

    public function clearBCBJPFIKPHG()
    {
        unset($this->BCBJPFIKPHG);
    }

    /**
     * Generated from protobuf field <code>.BNKNFJKMJIE BCBJPFIKPHG = 12;</code>
     * @param \BNKNFJKMJIE $var
     * @return $this
     */
    public function setBCBJPFIKPHG($var)
    {
        GPBUtil::checkMessage($var, \BNKNFJKMJIE::class);
        $this->BCBJPFIKPHG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LMPHODOEHCN APLCCKHHPKC = 1;</code>
     * @return \LMPHODOEHCN|null
     */
    public function getAPLCCKHHPKC()
    {
        return $this->APLCCKHHPKC;
    }

    public function hasAPLCCKHHPKC()
    {
        return isset($this->APLCCKHHPKC);
    }

    public function clearAPLCCKHHPKC()
    {
        unset($this->APLCCKHHPKC);
    }

    /**
     * Generated from protobuf field <code>.LMPHODOEHCN APLCCKHHPKC = 1;</code>
     * @param \LMPHODOEHCN $var
     * @return $this
     */
    public function setAPLCCKHHPKC($var)
    {
        GPBUtil::checkMessage($var, \LMPHODOEHCN::class);
        $this->APLCCKHHPKC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 14;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IFNCHAPEMHD PPAEOCBACHN = 15;</code>
     * @return \IFNCHAPEMHD|null
     */
    public function getPPAEOCBACHN()
    {
        return $this->PPAEOCBACHN;
    }

    public function hasPPAEOCBACHN()
    {
        return isset($this->PPAEOCBACHN);
    }

    public function clearPPAEOCBACHN()
    {
        unset($this->PPAEOCBACHN);
    }

    /**
     * Generated from protobuf field <code>.IFNCHAPEMHD PPAEOCBACHN = 15;</code>
     * @param \IFNCHAPEMHD $var
     * @return $this
     */
    public function setPPAEOCBACHN($var)
    {
        GPBUtil::checkMessage($var, \IFNCHAPEMHD::class);
        $this->PPAEOCBACHN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.JGNAJFOGFBJ DBBDJBPBJPA = 8;</code>
     * @return \JGNAJFOGFBJ|null
     */
    public function getDBBDJBPBJPA()
    {
        return $this->DBBDJBPBJPA;
    }

    public function hasDBBDJBPBJPA()
    {
        return isset($this->DBBDJBPBJPA);
    }

    public function clearDBBDJBPBJPA()
    {
        unset($this->DBBDJBPBJPA);
    }

    /**
     * Generated from protobuf field <code>.JGNAJFOGFBJ DBBDJBPBJPA = 8;</code>
     * @param \JGNAJFOGFBJ $var
     * @return $this
     */
    public function setDBBDJBPBJPA($var)
    {
        GPBUtil::checkMessage($var, \JGNAJFOGFBJ::class);
        $this->DBBDJBPBJPA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FBGHJICBPMN BDAJBMAANIN = 11;</code>
     * @return \FBGHJICBPMN|null
     */
    public function getBDAJBMAANIN()
    {
        return $this->BDAJBMAANIN;
    }

    public function hasBDAJBMAANIN()
    {
        return isset($this->BDAJBMAANIN);
    }

    public function clearBDAJBMAANIN()
    {
        unset($this->BDAJBMAANIN);
    }

    /**
     * Generated from protobuf field <code>.FBGHJICBPMN BDAJBMAANIN = 11;</code>
     * @param \FBGHJICBPMN $var
     * @return $this
     */
    public function setBDAJBMAANIN($var)
    {
        GPBUtil::checkMessage($var, \FBGHJICBPMN::class);
        $this->BDAJBMAANIN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AGFNMLEBEJD KACLLKAKKKO = 13;</code>
     * @return \AGFNMLEBEJD|null
     */
    public function getKACLLKAKKKO()
    {
        return $this->KACLLKAKKKO;
    }

    public function hasKACLLKAKKKO()
    {
        return isset($this->KACLLKAKKKO);
    }

    public function clearKACLLKAKKKO()
    {
        unset($this->KACLLKAKKKO);
    }

    /**
     * Generated from protobuf field <code>.AGFNMLEBEJD KACLLKAKKKO = 13;</code>
     * @param \AGFNMLEBEJD $var
     * @return $this
     */
    public function setKACLLKAKKKO($var)
    {
        GPBUtil::checkMessage($var, \AGFNMLEBEJD::class);
        $this->KACLLKAKKKO = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.APKPMOHIBKJ JOCEJHGHLEM = 9;</code>
     * @return \APKPMOHIBKJ|null
     */
    public function getJOCEJHGHLEM()
    {
        return $this->JOCEJHGHLEM;
    }

    public function hasJOCEJHGHLEM()
    {
        return isset($this->JOCEJHGHLEM);
    }

    public function clearJOCEJHGHLEM()
    {
        unset($this->JOCEJHGHLEM);
    }

    /**
     * Generated from protobuf field <code>.APKPMOHIBKJ JOCEJHGHLEM = 9;</code>
     * @param \APKPMOHIBKJ $var
     * @return $this
     */
    public function setJOCEJHGHLEM($var)
    {
        GPBUtil::checkMessage($var, \APKPMOHIBKJ::class);
        $this->JOCEJHGHLEM = $var;

        return $this;
    }

}

