<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EACHHLJGLGI</code>
 */
class EACHHLJGLGI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OJNBGOAJBAL KIHFIIMHNIF = 1;</code>
     */
    protected $KIHFIIMHNIF = null;
    /**
     * Generated from protobuf field <code>.IGDCHFEJDNA KMCCBAHLDFL = 12;</code>
     */
    protected $KMCCBAHLDFL = null;
    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 5;</code>
     */
    protected $NMJLDCHMDPE = null;
    /**
     * Generated from protobuf field <code>.GDHMBEFBPHM NEMGEOPCBAO = 2;</code>
     */
    protected $NEMGEOPCBAO = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OJNBGOAJBAL $KIHFIIMHNIF
     *     @type \IGDCHFEJDNA $KMCCBAHLDFL
     *     @type \NEKEEJIKGKJ $NMJLDCHMDPE
     *     @type \GDHMBEFBPHM $NEMGEOPCBAO
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OJNBGOAJBAL KIHFIIMHNIF = 1;</code>
     * @return \OJNBGOAJBAL|null
     */
    public function getKIHFIIMHNIF()
    {
        return $this->KIHFIIMHNIF;
    }

    public function hasKIHFIIMHNIF()
    {
        return isset($this->KIHFIIMHNIF);
    }

    public function clearKIHFIIMHNIF()
    {
        unset($this->KIHFIIMHNIF);
    }

    /**
     * Generated from protobuf field <code>.OJNBGOAJBAL KIHFIIMHNIF = 1;</code>
     * @param \OJNBGOAJBAL $var
     * @return $this
     */
    public function setKIHFIIMHNIF($var)
    {
        GPBUtil::checkMessage($var, \OJNBGOAJBAL::class);
        $this->KIHFIIMHNIF = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IGDCHFEJDNA KMCCBAHLDFL = 12;</code>
     * @return \IGDCHFEJDNA|null
     */
    public function getKMCCBAHLDFL()
    {
        return $this->KMCCBAHLDFL;
    }

    public function hasKMCCBAHLDFL()
    {
        return isset($this->KMCCBAHLDFL);
    }

    public function clearKMCCBAHLDFL()
    {
        unset($this->KMCCBAHLDFL);
    }

    /**
     * Generated from protobuf field <code>.IGDCHFEJDNA KMCCBAHLDFL = 12;</code>
     * @param \IGDCHFEJDNA $var
     * @return $this
     */
    public function setKMCCBAHLDFL($var)
    {
        GPBUtil::checkMessage($var, \IGDCHFEJDNA::class);
        $this->KMCCBAHLDFL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 5;</code>
     * @return \NEKEEJIKGKJ|null
     */
    public function getNMJLDCHMDPE()
    {
        return $this->NMJLDCHMDPE;
    }

    public function hasNMJLDCHMDPE()
    {
        return isset($this->NMJLDCHMDPE);
    }

    public function clearNMJLDCHMDPE()
    {
        unset($this->NMJLDCHMDPE);
    }

    /**
     * Generated from protobuf field <code>.NEKEEJIKGKJ NMJLDCHMDPE = 5;</code>
     * @param \NEKEEJIKGKJ $var
     * @return $this
     */
    public function setNMJLDCHMDPE($var)
    {
        GPBUtil::checkMessage($var, \NEKEEJIKGKJ::class);
        $this->NMJLDCHMDPE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GDHMBEFBPHM NEMGEOPCBAO = 2;</code>
     * @return \GDHMBEFBPHM|null
     */
    public function getNEMGEOPCBAO()
    {
        return $this->NEMGEOPCBAO;
    }

    public function hasNEMGEOPCBAO()
    {
        return isset($this->NEMGEOPCBAO);
    }

    public function clearNEMGEOPCBAO()
    {
        unset($this->NEMGEOPCBAO);
    }

    /**
     * Generated from protobuf field <code>.GDHMBEFBPHM NEMGEOPCBAO = 2;</code>
     * @param \GDHMBEFBPHM $var
     * @return $this
     */
    public function setNEMGEOPCBAO($var)
    {
        GPBUtil::checkMessage($var, \GDHMBEFBPHM::class);
        $this->NEMGEOPCBAO = $var;

        return $this;
    }

}

