<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EADIPAJCNCI</code>
 */
class EADIPAJCNCI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 AHKELHDHOCP = 5;</code>
     */
    protected $AHKELHDHOCP = 0;
    /**
     * Generated from protobuf field <code>.ICKIJPPDPPE status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $AHKELHDHOCP
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 AHKELHDHOCP = 5;</code>
     * @return int
     */
    public function getAHKELHDHOCP()
    {
        return $this->AHKELHDHOCP;
    }

    /**
     * Generated from protobuf field <code>uint32 AHKELHDHOCP = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAHKELHDHOCP($var)
    {
        GPBUtil::checkUint32($var);
        $this->AHKELHDHOCP = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ICKIJPPDPPE status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.ICKIJPPDPPE status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \ICKIJPPDPPE::class);
        $this->status = $var;

        return $this;
    }

}

