<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EALBGFMGCEG</code>
 */
class EALBGFMGCEG extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 level = 8;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>uint32 reward_display_type = 10;</code>
     */
    protected $reward_display_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $level
     *     @type int $reward_display_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 level = 8;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 reward_display_type = 10;</code>
     * @return int
     */
    public function getRewardDisplayType()
    {
        return $this->reward_display_type;
    }

    /**
     * Generated from protobuf field <code>uint32 reward_display_type = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRewardDisplayType($var)
    {
        GPBUtil::checkUint32($var);
        $this->reward_display_type = $var;

        return $this;
    }

}

