<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EANDFLDHCPB</code>
 */
class EANDFLDHCPB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>repeated .JBJMNMFPLPH JKDIGGIABMB = 5;</code>
     */
    private $JKDIGGIABMB;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type array<\JBJMNMFPLPH>|\Google\Protobuf\Internal\RepeatedField $JKDIGGIABMB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .JBJMNMFPLPH JKDIGGIABMB = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJKDIGGIABMB()
    {
        return $this->JKDIGGIABMB;
    }

    /**
     * Generated from protobuf field <code>repeated .JBJMNMFPLPH JKDIGGIABMB = 5;</code>
     * @param array<\JBJMNMFPLPH>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJKDIGGIABMB($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \JBJMNMFPLPH::class);
        $this->JKDIGGIABMB = $arr;

        return $this;
    }

}

