<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EBIHABDIGIO</code>
 */
class EBIHABDIGIO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool BJADALJFKAB = 7;</code>
     */
    protected $BJADALJFKAB = false;
    /**
     * Generated from protobuf field <code>bool AAFJGNNAPFC = 11;</code>
     */
    protected $AAFJGNNAPFC = false;
    /**
     * Generated from protobuf field <code>bool LEALOPKFPPE = 12;</code>
     */
    protected $LEALOPKFPPE = false;
    /**
     * Generated from protobuf field <code>bool GIGFGKBKNJD = 4;</code>
     */
    protected $GIGFGKBKNJD = false;
    /**
     * Generated from protobuf field <code>bool DEMOBHBJNDI = 9;</code>
     */
    protected $DEMOBHBJNDI = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $BJADALJFKAB
     *     @type bool $AAFJGNNAPFC
     *     @type bool $LEALOPKFPPE
     *     @type bool $GIGFGKBKNJD
     *     @type bool $DEMOBHBJNDI
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool BJADALJFKAB = 7;</code>
     * @return bool
     */
    public function getBJADALJFKAB()
    {
        return $this->BJADALJFKAB;
    }

    /**
     * Generated from protobuf field <code>bool BJADALJFKAB = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setBJADALJFKAB($var)
    {
        GPBUtil::checkBool($var);
        $this->BJADALJFKAB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool AAFJGNNAPFC = 11;</code>
     * @return bool
     */
    public function getAAFJGNNAPFC()
    {
        return $this->AAFJGNNAPFC;
    }

    /**
     * Generated from protobuf field <code>bool AAFJGNNAPFC = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setAAFJGNNAPFC($var)
    {
        GPBUtil::checkBool($var);
        $this->AAFJGNNAPFC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool LEALOPKFPPE = 12;</code>
     * @return bool
     */
    public function getLEALOPKFPPE()
    {
        return $this->LEALOPKFPPE;
    }

    /**
     * Generated from protobuf field <code>bool LEALOPKFPPE = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setLEALOPKFPPE($var)
    {
        GPBUtil::checkBool($var);
        $this->LEALOPKFPPE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool GIGFGKBKNJD = 4;</code>
     * @return bool
     */
    public function getGIGFGKBKNJD()
    {
        return $this->GIGFGKBKNJD;
    }

    /**
     * Generated from protobuf field <code>bool GIGFGKBKNJD = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setGIGFGKBKNJD($var)
    {
        GPBUtil::checkBool($var);
        $this->GIGFGKBKNJD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DEMOBHBJNDI = 9;</code>
     * @return bool
     */
    public function getDEMOBHBJNDI()
    {
        return $this->DEMOBHBJNDI;
    }

    /**
     * Generated from protobuf field <code>bool DEMOBHBJNDI = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setDEMOBHBJNDI($var)
    {
        GPBUtil::checkBool($var);
        $this->DEMOBHBJNDI = $var;

        return $this;
    }

}

