<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EBJPELAONKH</code>
 */
class EBJPELAONKH extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 avatar_id = 1;</code>
     */
    protected $avatar_id = 0;
    /**
     * Generated from protobuf field <code>uint32 bkbenaeiadb = 2;</code>
     */
    protected $bkbenaeiadb = 0;
    /**
     * Generated from protobuf field <code>uint32 total_turns = 3;</code>
     */
    protected $total_turns = 0;
    /**
     * Generated from protobuf field <code>double pihkhgjeplc = 4;</code>
     */
    protected $pihkhgjeplc = 0.0;
    /**
     * Generated from protobuf field <code>repeated .SkillUseProperty skill_times = 5;</code>
     */
    private $skill_times;
    /**
     * Generated from protobuf field <code>double total_damage = 6;</code>
     */
    protected $total_damage = 0.0;
    /**
     * Generated from protobuf field <code>double total_break_damage = 7;</code>
     */
    protected $total_break_damage = 0.0;
    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_damage = 8;</code>
     */
    private $attack_type_damage;
    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_break_damage = 9;</code>
     */
    private $attack_type_break_damage;
    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_max_damage = 10;</code>
     */
    private $attack_type_max_damage;
    /**
     * Generated from protobuf field <code>double total_damage_taken = 11;</code>
     */
    protected $total_damage_taken = 0.0;
    /**
     * Generated from protobuf field <code>double total_heal = 12;</code>
     */
    protected $total_heal = 0.0;
    /**
     * Generated from protobuf field <code>double total_hp_recover = 13;</code>
     */
    protected $total_hp_recover = 0.0;
    /**
     * Generated from protobuf field <code>double total_shield = 14;</code>
     */
    protected $total_shield = 0.0;
    /**
     * Generated from protobuf field <code>double total_shield_taken = 15;</code>
     */
    protected $total_shield_taken = 0.0;
    /**
     * Generated from protobuf field <code>double total_shield_damage = 16;</code>
     */
    protected $total_shield_damage = 0.0;
    /**
     * Generated from protobuf field <code>uint32 break_times = 17;</code>
     */
    protected $break_times = 0;
    /**
     * Generated from protobuf field <code>uint32 bccmhajkiof = 18;</code>
     */
    protected $bccmhajkiof = 0;
    /**
     * Generated from protobuf field <code>uint32 joobdaimbje = 19;</code>
     */
    protected $joobdaimbje = 0;
    /**
     * Generated from protobuf field <code>uint32 oajackjjcgp = 20;</code>
     */
    protected $oajackjjcgp = 0;
    /**
     * Generated from protobuf field <code>double jkehimgbdaf = 21;</code>
     */
    protected $jkehimgbdaf = 0.0;
    /**
     * Generated from protobuf field <code>uint32 entity_id = 22;</code>
     */
    protected $entity_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $avatar_id
     *     @type int $bkbenaeiadb
     *     @type int $total_turns
     *     @type float $pihkhgjeplc
     *     @type array<\SkillUseProperty>|\Google\Protobuf\Internal\RepeatedField $skill_times
     *     @type float $total_damage
     *     @type float $total_break_damage
     *     @type array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $attack_type_damage
     *     @type array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $attack_type_break_damage
     *     @type array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $attack_type_max_damage
     *     @type float $total_damage_taken
     *     @type float $total_heal
     *     @type float $total_hp_recover
     *     @type float $total_shield
     *     @type float $total_shield_taken
     *     @type float $total_shield_damage
     *     @type int $break_times
     *     @type int $bccmhajkiof
     *     @type int $joobdaimbje
     *     @type int $oajackjjcgp
     *     @type float $jkehimgbdaf
     *     @type int $entity_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_id = 1;</code>
     * @return int
     */
    public function getAvatarId()
    {
        return $this->avatar_id;
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAvatarId($var)
    {
        GPBUtil::checkUint32($var);
        $this->avatar_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bkbenaeiadb = 2;</code>
     * @return int
     */
    public function getBkbenaeiadb()
    {
        return $this->bkbenaeiadb;
    }

    /**
     * Generated from protobuf field <code>uint32 bkbenaeiadb = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBkbenaeiadb($var)
    {
        GPBUtil::checkUint32($var);
        $this->bkbenaeiadb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_turns = 3;</code>
     * @return int
     */
    public function getTotalTurns()
    {
        return $this->total_turns;
    }

    /**
     * Generated from protobuf field <code>uint32 total_turns = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalTurns($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_turns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double pihkhgjeplc = 4;</code>
     * @return float
     */
    public function getPihkhgjeplc()
    {
        return $this->pihkhgjeplc;
    }

    /**
     * Generated from protobuf field <code>double pihkhgjeplc = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPihkhgjeplc($var)
    {
        GPBUtil::checkDouble($var);
        $this->pihkhgjeplc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SkillUseProperty skill_times = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSkillTimes()
    {
        return $this->skill_times;
    }

    /**
     * Generated from protobuf field <code>repeated .SkillUseProperty skill_times = 5;</code>
     * @param array<\SkillUseProperty>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSkillTimes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SkillUseProperty::class);
        $this->skill_times = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_damage = 6;</code>
     * @return float
     */
    public function getTotalDamage()
    {
        return $this->total_damage;
    }

    /**
     * Generated from protobuf field <code>double total_damage = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalDamage($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_damage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_break_damage = 7;</code>
     * @return float
     */
    public function getTotalBreakDamage()
    {
        return $this->total_break_damage;
    }

    /**
     * Generated from protobuf field <code>double total_break_damage = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalBreakDamage($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_break_damage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_damage = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttackTypeDamage()
    {
        return $this->attack_type_damage;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_damage = 8;</code>
     * @param array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttackTypeDamage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AttackDamageProperty::class);
        $this->attack_type_damage = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_break_damage = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttackTypeBreakDamage()
    {
        return $this->attack_type_break_damage;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_break_damage = 9;</code>
     * @param array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttackTypeBreakDamage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AttackDamageProperty::class);
        $this->attack_type_break_damage = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_max_damage = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttackTypeMaxDamage()
    {
        return $this->attack_type_max_damage;
    }

    /**
     * Generated from protobuf field <code>repeated .AttackDamageProperty attack_type_max_damage = 10;</code>
     * @param array<\AttackDamageProperty>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttackTypeMaxDamage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AttackDamageProperty::class);
        $this->attack_type_max_damage = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_damage_taken = 11;</code>
     * @return float
     */
    public function getTotalDamageTaken()
    {
        return $this->total_damage_taken;
    }

    /**
     * Generated from protobuf field <code>double total_damage_taken = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalDamageTaken($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_damage_taken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_heal = 12;</code>
     * @return float
     */
    public function getTotalHeal()
    {
        return $this->total_heal;
    }

    /**
     * Generated from protobuf field <code>double total_heal = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalHeal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_heal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_hp_recover = 13;</code>
     * @return float
     */
    public function getTotalHpRecover()
    {
        return $this->total_hp_recover;
    }

    /**
     * Generated from protobuf field <code>double total_hp_recover = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalHpRecover($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_hp_recover = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_shield = 14;</code>
     * @return float
     */
    public function getTotalShield()
    {
        return $this->total_shield;
    }

    /**
     * Generated from protobuf field <code>double total_shield = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalShield($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_shield = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_shield_taken = 15;</code>
     * @return float
     */
    public function getTotalShieldTaken()
    {
        return $this->total_shield_taken;
    }

    /**
     * Generated from protobuf field <code>double total_shield_taken = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalShieldTaken($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_shield_taken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_shield_damage = 16;</code>
     * @return float
     */
    public function getTotalShieldDamage()
    {
        return $this->total_shield_damage;
    }

    /**
     * Generated from protobuf field <code>double total_shield_damage = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalShieldDamage($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_shield_damage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 break_times = 17;</code>
     * @return int
     */
    public function getBreakTimes()
    {
        return $this->break_times;
    }

    /**
     * Generated from protobuf field <code>uint32 break_times = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setBreakTimes($var)
    {
        GPBUtil::checkUint32($var);
        $this->break_times = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bccmhajkiof = 18;</code>
     * @return int
     */
    public function getBccmhajkiof()
    {
        return $this->bccmhajkiof;
    }

    /**
     * Generated from protobuf field <code>uint32 bccmhajkiof = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setBccmhajkiof($var)
    {
        GPBUtil::checkUint32($var);
        $this->bccmhajkiof = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 joobdaimbje = 19;</code>
     * @return int
     */
    public function getJoobdaimbje()
    {
        return $this->joobdaimbje;
    }

    /**
     * Generated from protobuf field <code>uint32 joobdaimbje = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setJoobdaimbje($var)
    {
        GPBUtil::checkUint32($var);
        $this->joobdaimbje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 oajackjjcgp = 20;</code>
     * @return int
     */
    public function getOajackjjcgp()
    {
        return $this->oajackjjcgp;
    }

    /**
     * Generated from protobuf field <code>uint32 oajackjjcgp = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setOajackjjcgp($var)
    {
        GPBUtil::checkUint32($var);
        $this->oajackjjcgp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double jkehimgbdaf = 21;</code>
     * @return float
     */
    public function getJkehimgbdaf()
    {
        return $this->jkehimgbdaf;
    }

    /**
     * Generated from protobuf field <code>double jkehimgbdaf = 21;</code>
     * @param float $var
     * @return $this
     */
    public function setJkehimgbdaf($var)
    {
        GPBUtil::checkDouble($var);
        $this->jkehimgbdaf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 entity_id = 22;</code>
     * @return int
     */
    public function getEntityId()
    {
        return $this->entity_id;
    }

    /**
     * Generated from protobuf field <code>uint32 entity_id = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkUint32($var);
        $this->entity_id = $var;

        return $this;
    }

}

