<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EFINDLMBMBF</code>
 */
class EFINDLMBMBF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 gddbplgkimf = 4;</code>
     */
    protected $gddbplgkimf = 0;
    /**
     * Generated from protobuf field <code>map<uint32, .ItemCostData> jdigocehgko = 6;</code>
     */
    private $jdigocehgko;
    /**
     * Generated from protobuf field <code>.ItemCostData kfhpbgllikp = 15;</code>
     */
    protected $kfhpbgllikp = null;
    /**
     * Generated from protobuf field <code>int32 bmcinbknmfp = 1;</code>
     */
    protected $bmcinbknmfp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $gddbplgkimf
     *     @type array|\Google\Protobuf\Internal\MapField $jdigocehgko
     *     @type \ItemCostData $kfhpbgllikp
     *     @type int $bmcinbknmfp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 gddbplgkimf = 4;</code>
     * @return int
     */
    public function getGddbplgkimf()
    {
        return $this->gddbplgkimf;
    }

    /**
     * Generated from protobuf field <code>uint32 gddbplgkimf = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGddbplgkimf($var)
    {
        GPBUtil::checkUint32($var);
        $this->gddbplgkimf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .ItemCostData> jdigocehgko = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getJdigocehgko()
    {
        return $this->jdigocehgko;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .ItemCostData> jdigocehgko = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setJdigocehgko($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \ItemCostData::class);
        $this->jdigocehgko = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemCostData kfhpbgllikp = 15;</code>
     * @return \ItemCostData|null
     */
    public function getKfhpbgllikp()
    {
        return $this->kfhpbgllikp;
    }

    public function hasKfhpbgllikp()
    {
        return isset($this->kfhpbgllikp);
    }

    public function clearKfhpbgllikp()
    {
        unset($this->kfhpbgllikp);
    }

    /**
     * Generated from protobuf field <code>.ItemCostData kfhpbgllikp = 15;</code>
     * @param \ItemCostData $var
     * @return $this
     */
    public function setKfhpbgllikp($var)
    {
        GPBUtil::checkMessage($var, \ItemCostData::class);
        $this->kfhpbgllikp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bmcinbknmfp = 1;</code>
     * @return int
     */
    public function getBmcinbknmfp()
    {
        return $this->bmcinbknmfp;
    }

    /**
     * Generated from protobuf field <code>int32 bmcinbknmfp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBmcinbknmfp($var)
    {
        GPBUtil::checkInt32($var);
        $this->bmcinbknmfp = $var;

        return $this;
    }

}

