<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EGKBHBFHPGN</code>
 */
class EGKBHBFHPGN extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 wave = 9;</code>
     */
    protected $wave = 0;
    /**
     * Generated from protobuf field <code>uint32 AHLKBKEFGII = 10;</code>
     */
    protected $AHLKBKEFGII = 0;
    /**
     * Generated from protobuf field <code>uint32 world_level = 11;</code>
     */
    protected $world_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $wave
     *     @type int $AHLKBKEFGII
     *     @type int $world_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 wave = 9;</code>
     * @return int
     */
    public function getWave()
    {
        return $this->wave;
    }

    /**
     * Generated from protobuf field <code>uint32 wave = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setWave($var)
    {
        GPBUtil::checkUint32($var);
        $this->wave = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 AHLKBKEFGII = 10;</code>
     * @return int
     */
    public function getAHLKBKEFGII()
    {
        return $this->AHLKBKEFGII;
    }

    /**
     * Generated from protobuf field <code>uint32 AHLKBKEFGII = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setAHLKBKEFGII($var)
    {
        GPBUtil::checkUint32($var);
        $this->AHLKBKEFGII = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 11;</code>
     * @return int
     */
    public function getWorldLevel()
    {
        return $this->world_level;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setWorldLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->world_level = $var;

        return $this;
    }

}

