<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ELKFOBFELAD</code>
 */
class ELKFOBFELAD extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ItemList reward = 6;</code>
     */
    protected $reward = null;
    /**
     * Generated from protobuf field <code>.ItemList HAJEJEFLKJD = 4;</code>
     */
    protected $HAJEJEFLKJD = null;
    /**
     * Generated from protobuf field <code>uint32 NPNHJLGFMIM = 13;</code>
     */
    protected $NPNHJLGFMIM = 0;
    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ItemList $reward
     *     @type \ItemList $HAJEJEFLKJD
     *     @type int $NPNHJLGFMIM
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 6;</code>
     * @return \ItemList|null
     */
    public function getReward()
    {
        return $this->reward;
    }

    public function hasReward()
    {
        return isset($this->reward);
    }

    public function clearReward()
    {
        unset($this->reward);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 6;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemList HAJEJEFLKJD = 4;</code>
     * @return \ItemList|null
     */
    public function getHAJEJEFLKJD()
    {
        return $this->HAJEJEFLKJD;
    }

    public function hasHAJEJEFLKJD()
    {
        return isset($this->HAJEJEFLKJD);
    }

    public function clearHAJEJEFLKJD()
    {
        unset($this->HAJEJEFLKJD);
    }

    /**
     * Generated from protobuf field <code>.ItemList HAJEJEFLKJD = 4;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setHAJEJEFLKJD($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->HAJEJEFLKJD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 NPNHJLGFMIM = 13;</code>
     * @return int
     */
    public function getNPNHJLGFMIM()
    {
        return $this->NPNHJLGFMIM;
    }

    /**
     * Generated from protobuf field <code>uint32 NPNHJLGFMIM = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setNPNHJLGFMIM($var)
    {
        GPBUtil::checkUint32($var);
        $this->NPNHJLGFMIM = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

