<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EMHPHALEBDL</code>
 */
class EMHPHALEBDL extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 AGALDAOBBKL = 9;</code>
     */
    protected $AGALDAOBBKL = 0;
    /**
     * Generated from protobuf field <code>map<uint32, bool> OKGBOHICKGA = 15;</code>
     */
    private $OKGBOHICKGA;
    /**
     * Generated from protobuf field <code>int32 KLIHFJGLCDI = 13;</code>
     */
    protected $KLIHFJGLCDI = 0;
    /**
     * Generated from protobuf field <code>.ItemCostData item_cost_list = 6;</code>
     */
    protected $item_cost_list = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $AGALDAOBBKL
     *     @type array|\Google\Protobuf\Internal\MapField $OKGBOHICKGA
     *     @type int $KLIHFJGLCDI
     *     @type \ItemCostData $item_cost_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 AGALDAOBBKL = 9;</code>
     * @return int
     */
    public function getAGALDAOBBKL()
    {
        return $this->AGALDAOBBKL;
    }

    /**
     * Generated from protobuf field <code>uint32 AGALDAOBBKL = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setAGALDAOBBKL($var)
    {
        GPBUtil::checkUint32($var);
        $this->AGALDAOBBKL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, bool> OKGBOHICKGA = 15;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOKGBOHICKGA()
    {
        return $this->OKGBOHICKGA;
    }

    /**
     * Generated from protobuf field <code>map<uint32, bool> OKGBOHICKGA = 15;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOKGBOHICKGA($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->OKGBOHICKGA = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 KLIHFJGLCDI = 13;</code>
     * @return int
     */
    public function getKLIHFJGLCDI()
    {
        return $this->KLIHFJGLCDI;
    }

    /**
     * Generated from protobuf field <code>int32 KLIHFJGLCDI = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setKLIHFJGLCDI($var)
    {
        GPBUtil::checkInt32($var);
        $this->KLIHFJGLCDI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemCostData item_cost_list = 6;</code>
     * @return \ItemCostData|null
     */
    public function getItemCostList()
    {
        return $this->item_cost_list;
    }

    public function hasItemCostList()
    {
        return isset($this->item_cost_list);
    }

    public function clearItemCostList()
    {
        unset($this->item_cost_list);
    }

    /**
     * Generated from protobuf field <code>.ItemCostData item_cost_list = 6;</code>
     * @param \ItemCostData $var
     * @return $this
     */
    public function setItemCostList($var)
    {
        GPBUtil::checkMessage($var, \ItemCostData::class);
        $this->item_cost_list = $var;

        return $this;
    }

}

