<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * GPNCBHKPELD (4425)
 *
 * Generated from protobuf message <code>EnterTreasureDungeonScRsp</code>
 */
class EnterTreasureDungeonScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.GOPDMKGLFGO jbhmijinepf = 15;</code>
     */
    protected $jbhmijinepf = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type \GOPDMKGLFGO $jbhmijinepf
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GOPDMKGLFGO jbhmijinepf = 15;</code>
     * @return \GOPDMKGLFGO|null
     */
    public function getJbhmijinepf()
    {
        return $this->jbhmijinepf;
    }

    public function hasJbhmijinepf()
    {
        return isset($this->jbhmijinepf);
    }

    public function clearJbhmijinepf()
    {
        unset($this->jbhmijinepf);
    }

    /**
     * Generated from protobuf field <code>.GOPDMKGLFGO jbhmijinepf = 15;</code>
     * @param \GOPDMKGLFGO $var
     * @return $this
     */
    public function setJbhmijinepf($var)
    {
        GPBUtil::checkMessage($var, \GOPDMKGLFGO::class);
        $this->jbhmijinepf = $var;

        return $this;
    }

}

