<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EPHIOEIMEPB</code>
 */
class EPHIOEIMEPB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool apjgenoipnb = 1;</code>
     */
    protected $apjgenoipnb = false;
    /**
     * Generated from protobuf field <code>repeated uint32 hbcpoddmcpo = 2;</code>
     */
    private $hbcpoddmcpo;
    /**
     * Generated from protobuf field <code>uint32 ojkjhgejlek = 3;</code>
     */
    protected $ojkjhgejlek = 0;
    /**
     * Generated from protobuf field <code>uint32 lejnkcjgbec = 4;</code>
     */
    protected $lejnkcjgbec = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $apjgenoipnb
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $hbcpoddmcpo
     *     @type int $ojkjhgejlek
     *     @type int $lejnkcjgbec
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool apjgenoipnb = 1;</code>
     * @return bool
     */
    public function getApjgenoipnb()
    {
        return $this->apjgenoipnb;
    }

    /**
     * Generated from protobuf field <code>bool apjgenoipnb = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setApjgenoipnb($var)
    {
        GPBUtil::checkBool($var);
        $this->apjgenoipnb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hbcpoddmcpo = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHbcpoddmcpo()
    {
        return $this->hbcpoddmcpo;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hbcpoddmcpo = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHbcpoddmcpo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->hbcpoddmcpo = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ojkjhgejlek = 3;</code>
     * @return int
     */
    public function getOjkjhgejlek()
    {
        return $this->ojkjhgejlek;
    }

    /**
     * Generated from protobuf field <code>uint32 ojkjhgejlek = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOjkjhgejlek($var)
    {
        GPBUtil::checkUint32($var);
        $this->ojkjhgejlek = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lejnkcjgbec = 4;</code>
     * @return int
     */
    public function getLejnkcjgbec()
    {
        return $this->lejnkcjgbec;
    }

    /**
     * Generated from protobuf field <code>uint32 lejnkcjgbec = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLejnkcjgbec($var)
    {
        GPBUtil::checkUint32($var);
        $this->lejnkcjgbec = $var;

        return $this;
    }

}

