<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FCBMHIGCMHL</code>
 */
class FCBMHIGCMHL extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OMBKBBJGHDF relic_unique_id = 10;</code>
     */
    protected $relic_unique_id = 0;
    /**
     * Generated from protobuf field <code>uint32 BPGOFIPCNLA = 2;</code>
     */
    protected $BPGOFIPCNLA = 0;
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $relic_unique_id
     *     @type int $BPGOFIPCNLA
     *     @type int $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OMBKBBJGHDF relic_unique_id = 10;</code>
     * @return int
     */
    public function getRelicUniqueId()
    {
        return $this->relic_unique_id;
    }

    /**
     * Generated from protobuf field <code>.OMBKBBJGHDF relic_unique_id = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRelicUniqueId($var)
    {
        GPBUtil::checkEnum($var, \OMBKBBJGHDF::class);
        $this->relic_unique_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 BPGOFIPCNLA = 2;</code>
     * @return int
     */
    public function getBPGOFIPCNLA()
    {
        return $this->BPGOFIPCNLA;
    }

    /**
     * Generated from protobuf field <code>uint32 BPGOFIPCNLA = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBPGOFIPCNLA($var)
    {
        GPBUtil::checkUint32($var);
        $this->BPGOFIPCNLA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

}

