<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FCEELHJHACM</code>
 */
class FCEELHJHACM extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.ItemList DDKHJIJENLC = 7;</code>
     */
    protected $DDKHJIJENLC = null;
    /**
     * Generated from protobuf field <code>.AGMNDLBCMHJ KJFIGLJDJFP = 1;</code>
     */
    protected $KJFIGLJDJFP = null;
    /**
     * Generated from protobuf field <code>uint32 BICMJOBAJOJ = 13;</code>
     */
    protected $BICMJOBAJOJ = 0;
    /**
     * Generated from protobuf field <code>uint32 basic_type = 2;</code>
     */
    protected $basic_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type \ItemList $DDKHJIJENLC
     *     @type \AGMNDLBCMHJ $KJFIGLJDJFP
     *     @type int $BICMJOBAJOJ
     *     @type int $basic_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemList DDKHJIJENLC = 7;</code>
     * @return \ItemList|null
     */
    public function getDDKHJIJENLC()
    {
        return $this->DDKHJIJENLC;
    }

    public function hasDDKHJIJENLC()
    {
        return isset($this->DDKHJIJENLC);
    }

    public function clearDDKHJIJENLC()
    {
        unset($this->DDKHJIJENLC);
    }

    /**
     * Generated from protobuf field <code>.ItemList DDKHJIJENLC = 7;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setDDKHJIJENLC($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->DDKHJIJENLC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AGMNDLBCMHJ KJFIGLJDJFP = 1;</code>
     * @return \AGMNDLBCMHJ|null
     */
    public function getKJFIGLJDJFP()
    {
        return $this->KJFIGLJDJFP;
    }

    public function hasKJFIGLJDJFP()
    {
        return isset($this->KJFIGLJDJFP);
    }

    public function clearKJFIGLJDJFP()
    {
        unset($this->KJFIGLJDJFP);
    }

    /**
     * Generated from protobuf field <code>.AGMNDLBCMHJ KJFIGLJDJFP = 1;</code>
     * @param \AGMNDLBCMHJ $var
     * @return $this
     */
    public function setKJFIGLJDJFP($var)
    {
        GPBUtil::checkMessage($var, \AGMNDLBCMHJ::class);
        $this->KJFIGLJDJFP = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 BICMJOBAJOJ = 13;</code>
     * @return int
     */
    public function getBICMJOBAJOJ()
    {
        return $this->BICMJOBAJOJ;
    }

    /**
     * Generated from protobuf field <code>uint32 BICMJOBAJOJ = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setBICMJOBAJOJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->BICMJOBAJOJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 basic_type = 2;</code>
     * @return int
     */
    public function getBasicType()
    {
        return $this->basic_type;
    }

    /**
     * Generated from protobuf field <code>uint32 basic_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBasicType($var)
    {
        GPBUtil::checkUint32($var);
        $this->basic_type = $var;

        return $this;
    }

}

