<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FCFPNMGMLEB</code>
 */
class FCFPNMGMLEB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ADKIDBBBHNC mkmeaenlame = 13;</code>
     */
    protected $mkmeaenlame = null;
    /**
     * Generated from protobuf field <code>uint32 lmbpkeobmhk = 15;</code>
     */
    protected $lmbpkeobmhk = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ADKIDBBBHNC $mkmeaenlame
     *     @type int $lmbpkeobmhk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ADKIDBBBHNC mkmeaenlame = 13;</code>
     * @return \ADKIDBBBHNC|null
     */
    public function getMkmeaenlame()
    {
        return $this->mkmeaenlame;
    }

    public function hasMkmeaenlame()
    {
        return isset($this->mkmeaenlame);
    }

    public function clearMkmeaenlame()
    {
        unset($this->mkmeaenlame);
    }

    /**
     * Generated from protobuf field <code>.ADKIDBBBHNC mkmeaenlame = 13;</code>
     * @param \ADKIDBBBHNC $var
     * @return $this
     */
    public function setMkmeaenlame($var)
    {
        GPBUtil::checkMessage($var, \ADKIDBBBHNC::class);
        $this->mkmeaenlame = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lmbpkeobmhk = 15;</code>
     * @return int
     */
    public function getLmbpkeobmhk()
    {
        return $this->lmbpkeobmhk;
    }

    /**
     * Generated from protobuf field <code>uint32 lmbpkeobmhk = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setLmbpkeobmhk($var)
    {
        GPBUtil::checkUint32($var);
        $this->lmbpkeobmhk = $var;

        return $this;
    }

}

