<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FEPJIODEGHH</code>
 */
class FEPJIODEGHH extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.HNGOJHBPFEJ PENKIFIKIAC = 12;</code>
     */
    protected $PENKIFIKIAC = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \HNGOJHBPFEJ $PENKIFIKIAC
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.HNGOJHBPFEJ PENKIFIKIAC = 12;</code>
     * @return \HNGOJHBPFEJ|null
     */
    public function getPENKIFIKIAC()
    {
        return $this->PENKIFIKIAC;
    }

    public function hasPENKIFIKIAC()
    {
        return isset($this->PENKIFIKIAC);
    }

    public function clearPENKIFIKIAC()
    {
        unset($this->PENKIFIKIAC);
    }

    /**
     * Generated from protobuf field <code>.HNGOJHBPFEJ PENKIFIKIAC = 12;</code>
     * @param \HNGOJHBPFEJ $var
     * @return $this
     */
    public function setPENKIFIKIAC($var)
    {
        GPBUtil::checkMessage($var, \HNGOJHBPFEJ::class);
        $this->PENKIFIKIAC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

