<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FNFHJPDBIEA</code>
 */
class FNFHJPDBIEA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 2;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.MJKBNJAKOJH ONBLCJEGCKF = 13;</code>
     */
    protected $ONBLCJEGCKF = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type \MJKBNJAKOJH $ONBLCJEGCKF
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 2;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MJKBNJAKOJH ONBLCJEGCKF = 13;</code>
     * @return \MJKBNJAKOJH|null
     */
    public function getONBLCJEGCKF()
    {
        return $this->ONBLCJEGCKF;
    }

    public function hasONBLCJEGCKF()
    {
        return isset($this->ONBLCJEGCKF);
    }

    public function clearONBLCJEGCKF()
    {
        unset($this->ONBLCJEGCKF);
    }

    /**
     * Generated from protobuf field <code>.MJKBNJAKOJH ONBLCJEGCKF = 13;</code>
     * @param \MJKBNJAKOJH $var
     * @return $this
     */
    public function setONBLCJEGCKF($var)
    {
        GPBUtil::checkMessage($var, \MJKBNJAKOJH::class);
        $this->ONBLCJEGCKF = $var;

        return $this;
    }

}

