<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LKDMHNABMLN (2940)
 *
 * Generated from protobuf message <code>GetFriendDevelopmentInfoScRsp</code>
 */
class GetFriendDevelopmentInfoScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .BHBEDKJMNED emdgmamejkb = 10;</code>
     */
    private $emdgmamejkb;
    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     */
    protected $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\BHBEDKJMNED>|\Google\Protobuf\Internal\RepeatedField $emdgmamejkb
     *     @type int $retcode
     *     @type int $uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .BHBEDKJMNED emdgmamejkb = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmdgmamejkb()
    {
        return $this->emdgmamejkb;
    }

    /**
     * Generated from protobuf field <code>repeated .BHBEDKJMNED emdgmamejkb = 10;</code>
     * @param array<\BHBEDKJMNED>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmdgmamejkb($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BHBEDKJMNED::class);
        $this->emdgmamejkb = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

}

