<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * JBODBOPJOLO (4710)
 *
 * Generated from protobuf message <code>GetSaveLogisticsMapScRsp</code>
 */
class GetSaveLogisticsMapScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GFDCMEBGCHI kcohmmblcgh = 10;</code>
     */
    private $kcohmmblcgh;
    /**
     * Generated from protobuf field <code>uint32 retcode = 7;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GFDCMEBGCHI>|\Google\Protobuf\Internal\RepeatedField $kcohmmblcgh
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GFDCMEBGCHI kcohmmblcgh = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKcohmmblcgh()
    {
        return $this->kcohmmblcgh;
    }

    /**
     * Generated from protobuf field <code>repeated .GFDCMEBGCHI kcohmmblcgh = 10;</code>
     * @param array<\GFDCMEBGCHI>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKcohmmblcgh($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GFDCMEBGCHI::class);
        $this->kcohmmblcgh = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 7;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

