<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GFDNEDJGODO</code>
 */
class GFDNEDJGODO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>bool CHMLHBJHONK = 8;</code>
     */
    protected $CHMLHBJHONK = false;
    /**
     * Generated from protobuf field <code>repeated .DODBAEALNDI DCECKPANHHB = 5;</code>
     */
    private $DCECKPANHHB;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type bool $CHMLHBJHONK
     *     @type array<\DODBAEALNDI>|\Google\Protobuf\Internal\RepeatedField $DCECKPANHHB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CHMLHBJHONK = 8;</code>
     * @return bool
     */
    public function getCHMLHBJHONK()
    {
        return $this->CHMLHBJHONK;
    }

    /**
     * Generated from protobuf field <code>bool CHMLHBJHONK = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setCHMLHBJHONK($var)
    {
        GPBUtil::checkBool($var);
        $this->CHMLHBJHONK = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .DODBAEALNDI DCECKPANHHB = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDCECKPANHHB()
    {
        return $this->DCECKPANHHB;
    }

    /**
     * Generated from protobuf field <code>repeated .DODBAEALNDI DCECKPANHHB = 5;</code>
     * @param array<\DODBAEALNDI>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDCECKPANHHB($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \DODBAEALNDI::class);
        $this->DCECKPANHHB = $arr;

        return $this;
    }

}

