<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HAPEOBJJPAF</code>
 */
class HAPEOBJJPAF extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool afepjbiopdl = 1;</code>
     */
    protected $afepjbiopdl = false;
    /**
     * Generated from protobuf field <code>map<string, .LDCPMBINOEO> kmibbnglipc = 2;</code>
     */
    private $kmibbnglipc;
    /**
     * Generated from protobuf field <code>bytes dfemmlkbabk = 3;</code>
     */
    protected $dfemmlkbabk = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $afepjbiopdl
     *     @type array|\Google\Protobuf\Internal\MapField $kmibbnglipc
     *     @type string $dfemmlkbabk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool afepjbiopdl = 1;</code>
     * @return bool
     */
    public function getAfepjbiopdl()
    {
        return $this->afepjbiopdl;
    }

    /**
     * Generated from protobuf field <code>bool afepjbiopdl = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAfepjbiopdl($var)
    {
        GPBUtil::checkBool($var);
        $this->afepjbiopdl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .LDCPMBINOEO> kmibbnglipc = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getKmibbnglipc()
    {
        return $this->kmibbnglipc;
    }

    /**
     * Generated from protobuf field <code>map<string, .LDCPMBINOEO> kmibbnglipc = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setKmibbnglipc($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \LDCPMBINOEO::class);
        $this->kmibbnglipc = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes dfemmlkbabk = 3;</code>
     * @return string
     */
    public function getDfemmlkbabk()
    {
        return $this->dfemmlkbabk;
    }

    /**
     * Generated from protobuf field <code>bytes dfemmlkbabk = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDfemmlkbabk($var)
    {
        GPBUtil::checkString($var, False);
        $this->dfemmlkbabk = $var;

        return $this;
    }

}

