<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HGJFIONFMBG</code>
 */
class HGJFIONFMBG extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 fhopjnkmnpb = 14;</code>
     */
    protected $fhopjnkmnpb = 0;
    /**
     * Generated from protobuf field <code>uint32 bkoliaijjgi = 11;</code>
     */
    protected $bkoliaijjgi = 0;
    /**
     * Generated from protobuf field <code>uint32 level = 1;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fhopjnkmnpb
     *     @type int $bkoliaijjgi
     *     @type int $level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 fhopjnkmnpb = 14;</code>
     * @return int
     */
    public function getFhopjnkmnpb()
    {
        return $this->fhopjnkmnpb;
    }

    /**
     * Generated from protobuf field <code>uint32 fhopjnkmnpb = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setFhopjnkmnpb($var)
    {
        GPBUtil::checkUint32($var);
        $this->fhopjnkmnpb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bkoliaijjgi = 11;</code>
     * @return int
     */
    public function getBkoliaijjgi()
    {
        return $this->bkoliaijjgi;
    }

    /**
     * Generated from protobuf field <code>uint32 bkoliaijjgi = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setBkoliaijjgi($var)
    {
        GPBUtil::checkUint32($var);
        $this->bkoliaijjgi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 1;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

}

