<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HHIMDMKHFHG</code>
 */
class HHIMDMKHFHG extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ANLMPHAOAHN = 15;</code>
     */
    protected $ANLMPHAOAHN = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ANLMPHAOAHN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ANLMPHAOAHN = 15;</code>
     * @return int
     */
    public function getANLMPHAOAHN()
    {
        return $this->ANLMPHAOAHN;
    }

    /**
     * Generated from protobuf field <code>uint32 ANLMPHAOAHN = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setANLMPHAOAHN($var)
    {
        GPBUtil::checkUint32($var);
        $this->ANLMPHAOAHN = $var;

        return $this;
    }

}

