<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HLCCNEHFDBA</code>
 */
class HLCCNEHFDBA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 entity_id = 11;</code>
     */
    protected $entity_id = 0;
    /**
     * Generated from protobuf field <code>bool pkfakhdpied = 10;</code>
     */
    protected $pkfakhdpied = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $entity_id
     *     @type bool $pkfakhdpied
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 entity_id = 11;</code>
     * @return int
     */
    public function getEntityId()
    {
        return $this->entity_id;
    }

    /**
     * Generated from protobuf field <code>uint32 entity_id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkUint32($var);
        $this->entity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool pkfakhdpied = 10;</code>
     * @return bool
     */
    public function getPkfakhdpied()
    {
        return $this->pkfakhdpied;
    }

    /**
     * Generated from protobuf field <code>bool pkfakhdpied = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setPkfakhdpied($var)
    {
        GPBUtil::checkBool($var);
        $this->pkfakhdpied = $var;

        return $this;
    }

}

