<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>IAMINGHLBDJ</code>
 */
class IAMINGHLBDJ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 level = 12;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>uint32 scepter_id = 2;</code>
     */
    protected $scepter_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $level
     *     @type int $scepter_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 level = 12;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 scepter_id = 2;</code>
     * @return int
     */
    public function getScepterId()
    {
        return $this->scepter_id;
    }

    /**
     * Generated from protobuf field <code>uint32 scepter_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setScepterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->scepter_id = $var;

        return $this;
    }

}

