<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ICMNCJPLGFN</code>
 */
class ICMNCJPLGFN extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 BNPOBEBNLJM = 12;</code>
     */
    protected $BNPOBEBNLJM = 0;
    /**
     * Generated from protobuf field <code>uint32 LEGLHJAFLHG = 7;</code>
     */
    protected $LEGLHJAFLHG = 0;
    /**
     * Generated from protobuf field <code>uint32 KOBNNGIMGEJ = 3;</code>
     */
    protected $KOBNNGIMGEJ = 0;
    /**
     * Generated from protobuf field <code>uint32 FFAACFIPNPH = 8;</code>
     */
    protected $FFAACFIPNPH = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $BNPOBEBNLJM
     *     @type int $LEGLHJAFLHG
     *     @type int $KOBNNGIMGEJ
     *     @type int $FFAACFIPNPH
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 BNPOBEBNLJM = 12;</code>
     * @return int
     */
    public function getBNPOBEBNLJM()
    {
        return $this->BNPOBEBNLJM;
    }

    /**
     * Generated from protobuf field <code>uint32 BNPOBEBNLJM = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setBNPOBEBNLJM($var)
    {
        GPBUtil::checkUint32($var);
        $this->BNPOBEBNLJM = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 LEGLHJAFLHG = 7;</code>
     * @return int
     */
    public function getLEGLHJAFLHG()
    {
        return $this->LEGLHJAFLHG;
    }

    /**
     * Generated from protobuf field <code>uint32 LEGLHJAFLHG = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLEGLHJAFLHG($var)
    {
        GPBUtil::checkUint32($var);
        $this->LEGLHJAFLHG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 KOBNNGIMGEJ = 3;</code>
     * @return int
     */
    public function getKOBNNGIMGEJ()
    {
        return $this->KOBNNGIMGEJ;
    }

    /**
     * Generated from protobuf field <code>uint32 KOBNNGIMGEJ = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setKOBNNGIMGEJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->KOBNNGIMGEJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 FFAACFIPNPH = 8;</code>
     * @return int
     */
    public function getFFAACFIPNPH()
    {
        return $this->FFAACFIPNPH;
    }

    /**
     * Generated from protobuf field <code>uint32 FFAACFIPNPH = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setFFAACFIPNPH($var)
    {
        GPBUtil::checkUint32($var);
        $this->FFAACFIPNPH = $var;

        return $this;
    }

}

