<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>IDONPJDHNNN</code>
 */
class IDONPJDHNNN extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PEFBCGPHGBG JOJMKBPLJPD = 6;</code>
     */
    protected $JOJMKBPLJPD = 0;
    /**
     * Generated from protobuf field <code>uint32 BIIHOBMMFDP = 11;</code>
     */
    protected $BIIHOBMMFDP = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $JOJMKBPLJPD
     *     @type int $BIIHOBMMFDP
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.PEFBCGPHGBG JOJMKBPLJPD = 6;</code>
     * @return int
     */
    public function getJOJMKBPLJPD()
    {
        return $this->JOJMKBPLJPD;
    }

    /**
     * Generated from protobuf field <code>.PEFBCGPHGBG JOJMKBPLJPD = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setJOJMKBPLJPD($var)
    {
        GPBUtil::checkEnum($var, \PEFBCGPHGBG::class);
        $this->JOJMKBPLJPD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 BIIHOBMMFDP = 11;</code>
     * @return int
     */
    public function getBIIHOBMMFDP()
    {
        return $this->BIIHOBMMFDP;
    }

    /**
     * Generated from protobuf field <code>uint32 BIIHOBMMFDP = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setBIIHOBMMFDP($var)
    {
        GPBUtil::checkUint32($var);
        $this->BIIHOBMMFDP = $var;

        return $this;
    }

}

