<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>IJOJNOOJCJG</code>
 */
class IJOJNOOJCJG extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.NNIDMJHAPKK DBBDJBPBJPA = 8;</code>
     */
    protected $DBBDJBPBJPA = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NNIDMJHAPKK $DBBDJBPBJPA
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.NNIDMJHAPKK DBBDJBPBJPA = 8;</code>
     * @return \NNIDMJHAPKK|null
     */
    public function getDBBDJBPBJPA()
    {
        return $this->DBBDJBPBJPA;
    }

    public function hasDBBDJBPBJPA()
    {
        return isset($this->DBBDJBPBJPA);
    }

    public function clearDBBDJBPBJPA()
    {
        unset($this->DBBDJBPBJPA);
    }

    /**
     * Generated from protobuf field <code>.NNIDMJHAPKK DBBDJBPBJPA = 8;</code>
     * @param \NNIDMJHAPKK $var
     * @return $this
     */
    public function setDBBDJBPBJPA($var)
    {
        GPBUtil::checkMessage($var, \NNIDMJHAPKK::class);
        $this->DBBDJBPBJPA = $var;

        return $this;
    }

}

