<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>INLEODPFKHB</code>
 */
class INLEODPFKHB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 bndmgiojoan = 5;</code>
     */
    protected $bndmgiojoan = 0;
    /**
     * Generated from protobuf field <code>.DIDGDCPGLDG cffmojghjlm = 4;</code>
     */
    protected $cffmojghjlm = null;
    /**
     * Generated from protobuf field <code>uint32 efccjkghjdk = 13;</code>
     */
    protected $efccjkghjdk = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $bndmgiojoan
     *     @type \DIDGDCPGLDG $cffmojghjlm
     *     @type int $efccjkghjdk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 bndmgiojoan = 5;</code>
     * @return int
     */
    public function getBndmgiojoan()
    {
        return $this->bndmgiojoan;
    }

    /**
     * Generated from protobuf field <code>uint32 bndmgiojoan = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBndmgiojoan($var)
    {
        GPBUtil::checkUint32($var);
        $this->bndmgiojoan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DIDGDCPGLDG cffmojghjlm = 4;</code>
     * @return \DIDGDCPGLDG|null
     */
    public function getCffmojghjlm()
    {
        return $this->cffmojghjlm;
    }

    public function hasCffmojghjlm()
    {
        return isset($this->cffmojghjlm);
    }

    public function clearCffmojghjlm()
    {
        unset($this->cffmojghjlm);
    }

    /**
     * Generated from protobuf field <code>.DIDGDCPGLDG cffmojghjlm = 4;</code>
     * @param \DIDGDCPGLDG $var
     * @return $this
     */
    public function setCffmojghjlm($var)
    {
        GPBUtil::checkMessage($var, \DIDGDCPGLDG::class);
        $this->cffmojghjlm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 efccjkghjdk = 13;</code>
     * @return int
     */
    public function getEfccjkghjdk()
    {
        return $this->efccjkghjdk;
    }

    /**
     * Generated from protobuf field <code>uint32 efccjkghjdk = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setEfccjkghjdk($var)
    {
        GPBUtil::checkUint32($var);
        $this->efccjkghjdk = $var;

        return $this;
    }

}

