<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

/**
 * Protobuf type <code>IOGDJDOBMOP</code>
 */
class IOGDJDOBMOP
{
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_DICE_SOURCE_TYPE_NONE = 0;</code>
     */
    const CHESS_ROGUE_DICE_SOURCE_TYPE_NONE = 0;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_DICE_SOURCE_TYPE_NORMAL = 1;</code>
     */
    const CHESS_ROGUE_DICE_SOURCE_TYPE_NORMAL = 1;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_DICE_SOURCE_TYPE_REPEAT = 2;</code>
     */
    const CHESS_ROGUE_DICE_SOURCE_TYPE_REPEAT = 2;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_DICE_SOURCE_TYPE_CHEAT = 3;</code>
     */
    const CHESS_ROGUE_DICE_SOURCE_TYPE_CHEAT = 3;

    private static $valueToName = [
        self::CHESS_ROGUE_DICE_SOURCE_TYPE_NONE => 'CHESS_ROGUE_DICE_SOURCE_TYPE_NONE',
        self::CHESS_ROGUE_DICE_SOURCE_TYPE_NORMAL => 'CHESS_ROGUE_DICE_SOURCE_TYPE_NORMAL',
        self::CHESS_ROGUE_DICE_SOURCE_TYPE_REPEAT => 'CHESS_ROGUE_DICE_SOURCE_TYPE_REPEAT',
        self::CHESS_ROGUE_DICE_SOURCE_TYPE_CHEAT => 'CHESS_ROGUE_DICE_SOURCE_TYPE_CHEAT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

