<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>JEFONPCOJLD</code>
 */
class JEFONPCOJLD extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OGMCFCJMIJE MODEHMLELLN = 8;</code>
     */
    protected $MODEHMLELLN = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 15;</code>
     */
    private $base_avatar_id_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OGMCFCJMIJE $MODEHMLELLN
     *     @type int $retcode
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $base_avatar_id_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OGMCFCJMIJE MODEHMLELLN = 8;</code>
     * @return \OGMCFCJMIJE|null
     */
    public function getMODEHMLELLN()
    {
        return $this->MODEHMLELLN;
    }

    public function hasMODEHMLELLN()
    {
        return isset($this->MODEHMLELLN);
    }

    public function clearMODEHMLELLN()
    {
        unset($this->MODEHMLELLN);
    }

    /**
     * Generated from protobuf field <code>.OGMCFCJMIJE MODEHMLELLN = 8;</code>
     * @param \OGMCFCJMIJE $var
     * @return $this
     */
    public function setMODEHMLELLN($var)
    {
        GPBUtil::checkMessage($var, \OGMCFCJMIJE::class);
        $this->MODEHMLELLN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBaseAvatarIdList()
    {
        return $this->base_avatar_id_list;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 15;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBaseAvatarIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->base_avatar_id_list = $arr;

        return $this;
    }

}

