<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

/**
 * Protobuf type <code>JLOEPEPJMDP</code>
 */
class JLOEPEPJMDP
{
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_NONE = 0;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_NONE = 0;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_NORMAL_FINISH = 1;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_NORMAL_FINISH = 1;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_NORMAL_QUIT = 2;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_NORMAL_QUIT = 2;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_DIALOG = 3;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_DIALOG = 3;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_FAILED = 4;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_FAILED = 4;
    /**
     * Generated from protobuf enum <code>CHESS_ROGUE_ACCOUNT_BY_CUSTOM_OP = 5;</code>
     */
    const CHESS_ROGUE_ACCOUNT_BY_CUSTOM_OP = 5;

    private static $valueToName = [
        self::CHESS_ROGUE_ACCOUNT_BY_NONE => 'CHESS_ROGUE_ACCOUNT_BY_NONE',
        self::CHESS_ROGUE_ACCOUNT_BY_NORMAL_FINISH => 'CHESS_ROGUE_ACCOUNT_BY_NORMAL_FINISH',
        self::CHESS_ROGUE_ACCOUNT_BY_NORMAL_QUIT => 'CHESS_ROGUE_ACCOUNT_BY_NORMAL_QUIT',
        self::CHESS_ROGUE_ACCOUNT_BY_DIALOG => 'CHESS_ROGUE_ACCOUNT_BY_DIALOG',
        self::CHESS_ROGUE_ACCOUNT_BY_FAILED => 'CHESS_ROGUE_ACCOUNT_BY_FAILED',
        self::CHESS_ROGUE_ACCOUNT_BY_CUSTOM_OP => 'CHESS_ROGUE_ACCOUNT_BY_CUSTOM_OP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

