<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>JOIEMKPMMGN</code>
 */
class JOIEMKPMMGN extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 aeon_id = 12;</code>
     */
    protected $aeon_id = 0;
    /**
     * Generated from protobuf field <code>uint32 eecemipjjgh = 14;</code>
     */
    protected $eecemipjjgh = 0;
    /**
     * Generated from protobuf field <code>uint32 exp = 13;</code>
     */
    protected $exp = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 opgbkmppjmp = 7;</code>
     */
    private $opgbkmppjmp;
    /**
     * Generated from protobuf field <code>uint32 level = 15;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 bocjbbdemfi = 8;</code>
     */
    private $bocjbbdemfi;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $aeon_id
     *     @type int $eecemipjjgh
     *     @type int $exp
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $opgbkmppjmp
     *     @type int $level
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $bocjbbdemfi
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 aeon_id = 12;</code>
     * @return int
     */
    public function getAeonId()
    {
        return $this->aeon_id;
    }

    /**
     * Generated from protobuf field <code>uint32 aeon_id = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setAeonId($var)
    {
        GPBUtil::checkUint32($var);
        $this->aeon_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 eecemipjjgh = 14;</code>
     * @return int
     */
    public function getEecemipjjgh()
    {
        return $this->eecemipjjgh;
    }

    /**
     * Generated from protobuf field <code>uint32 eecemipjjgh = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setEecemipjjgh($var)
    {
        GPBUtil::checkUint32($var);
        $this->eecemipjjgh = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 13;</code>
     * @return int
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkUint32($var);
        $this->exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 opgbkmppjmp = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOpgbkmppjmp()
    {
        return $this->opgbkmppjmp;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 opgbkmppjmp = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOpgbkmppjmp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->opgbkmppjmp = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 15;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 bocjbbdemfi = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBocjbbdemfi()
    {
        return $this->bocjbbdemfi;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 bocjbbdemfi = 8;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBocjbbdemfi($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->bocjbbdemfi = $arr;

        return $this;
    }

}

