<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KBFEOIAJLJC</code>
 */
class KBFEOIAJLJC extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 NCPFPAMHAOE = 14;</code>
     */
    protected $NCPFPAMHAOE = 0;
    /**
     * Generated from protobuf field <code>uint32 MOCKIOPKEKE = 6;</code>
     */
    protected $MOCKIOPKEKE = 0;
    /**
     * Generated from protobuf field <code>uint32 level = 7;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $NCPFPAMHAOE
     *     @type int $MOCKIOPKEKE
     *     @type int $level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 NCPFPAMHAOE = 14;</code>
     * @return int
     */
    public function getNCPFPAMHAOE()
    {
        return $this->NCPFPAMHAOE;
    }

    /**
     * Generated from protobuf field <code>uint32 NCPFPAMHAOE = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setNCPFPAMHAOE($var)
    {
        GPBUtil::checkUint32($var);
        $this->NCPFPAMHAOE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 MOCKIOPKEKE = 6;</code>
     * @return int
     */
    public function getMOCKIOPKEKE()
    {
        return $this->MOCKIOPKEKE;
    }

    /**
     * Generated from protobuf field <code>uint32 MOCKIOPKEKE = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMOCKIOPKEKE($var)
    {
        GPBUtil::checkUint32($var);
        $this->MOCKIOPKEKE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 7;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

}

