<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KHKPCCBKLNK</code>
 */
class KHKPCCBKLNK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>repeated .OMJJAFALBLM MEGOKDOCHJH = 10;</code>
     */
    private $MEGOKDOCHJH;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type array<\OMJJAFALBLM>|\Google\Protobuf\Internal\RepeatedField $MEGOKDOCHJH
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OMJJAFALBLM MEGOKDOCHJH = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMEGOKDOCHJH()
    {
        return $this->MEGOKDOCHJH;
    }

    /**
     * Generated from protobuf field <code>repeated .OMJJAFALBLM MEGOKDOCHJH = 10;</code>
     * @param array<\OMJJAFALBLM>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMEGOKDOCHJH($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OMJJAFALBLM::class);
        $this->MEGOKDOCHJH = $arr;

        return $this;
    }

}

