<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LDPBKMPNJFG</code>
 */
class LDPBKMPNJFG extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .INLEODPFKHB pepagojdnho = 8;</code>
     */
    private $pepagojdnho;
    /**
     * Generated from protobuf field <code>repeated .IAAOPDNACNB klhommbkljl = 4;</code>
     */
    private $klhommbkljl;
    /**
     * Generated from protobuf field <code>uint32 dkihhamkahk = 9;</code>
     */
    protected $dkihhamkahk = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\INLEODPFKHB>|\Google\Protobuf\Internal\RepeatedField $pepagojdnho
     *     @type array<\IAAOPDNACNB>|\Google\Protobuf\Internal\RepeatedField $klhommbkljl
     *     @type int $dkihhamkahk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .INLEODPFKHB pepagojdnho = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPepagojdnho()
    {
        return $this->pepagojdnho;
    }

    /**
     * Generated from protobuf field <code>repeated .INLEODPFKHB pepagojdnho = 8;</code>
     * @param array<\INLEODPFKHB>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPepagojdnho($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \INLEODPFKHB::class);
        $this->pepagojdnho = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .IAAOPDNACNB klhommbkljl = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKlhommbkljl()
    {
        return $this->klhommbkljl;
    }

    /**
     * Generated from protobuf field <code>repeated .IAAOPDNACNB klhommbkljl = 4;</code>
     * @param array<\IAAOPDNACNB>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKlhommbkljl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \IAAOPDNACNB::class);
        $this->klhommbkljl = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dkihhamkahk = 9;</code>
     * @return int
     */
    public function getDkihhamkahk()
    {
        return $this->dkihhamkahk;
    }

    /**
     * Generated from protobuf field <code>uint32 dkihhamkahk = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setDkihhamkahk($var)
    {
        GPBUtil::checkUint32($var);
        $this->dkihhamkahk = $var;

        return $this;
    }

}

