<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LLKOHFCICJB</code>
 */
class LLKOHFCICJB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .BattleAvatar avatar_list = 1;</code>
     */
    private $avatar_list;
    /**
     * Generated from protobuf field <code>repeated .BattleMonsterWave monster_wave_list = 2;</code>
     */
    private $monster_wave_list;
    /**
     * Generated from protobuf field <code>repeated .BattleBuff buff_list = 3;</code>
     */
    private $buff_list;
    /**
     * Generated from protobuf field <code>uint32 world_level = 7;</code>
     */
    protected $world_level = 0;
    /**
     * Generated from protobuf field <code>map<uint32, .JGOIHDOBEEK> PGKJOGNBOPO = 9;</code>
     */
    private $PGKJOGNBOPO;
    /**
     * Generated from protobuf field <code>.HMCNJLLHBLI LNEFJMMOMKB = 10;</code>
     */
    protected $LNEFJMMOMKB = null;
    /**
     * Generated from protobuf field <code>repeated .BattleAvatar JCFNBCABDNB = 11;</code>
     */
    private $JCFNBCABDNB;
    /**
     * Generated from protobuf field <code>.EvolveBuildBattleInfo KAHOEKAEFHD = 12;</code>
     */
    protected $KAHOEKAEFHD = null;
    /**
     * Generated from protobuf field <code>.KEJJGGCCGAN DHNDKIFPOLF = 13;</code>
     */
    protected $DHNDKIFPOLF = null;
    /**
     * Generated from protobuf field <code>.BIMKJOHKBNO EPECBKPMBHE = 14;</code>
     */
    protected $EPECBKPMBHE = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\BattleAvatar>|\Google\Protobuf\Internal\RepeatedField $avatar_list
     *     @type array<\BattleMonsterWave>|\Google\Protobuf\Internal\RepeatedField $monster_wave_list
     *     @type array<\BattleBuff>|\Google\Protobuf\Internal\RepeatedField $buff_list
     *     @type int $world_level
     *     @type array|\Google\Protobuf\Internal\MapField $PGKJOGNBOPO
     *     @type \HMCNJLLHBLI $LNEFJMMOMKB
     *     @type array<\BattleAvatar>|\Google\Protobuf\Internal\RepeatedField $JCFNBCABDNB
     *     @type \EvolveBuildBattleInfo $KAHOEKAEFHD
     *     @type \KEJJGGCCGAN $DHNDKIFPOLF
     *     @type \BIMKJOHKBNO $EPECBKPMBHE
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .BattleAvatar avatar_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvatarList()
    {
        return $this->avatar_list;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleAvatar avatar_list = 1;</code>
     * @param array<\BattleAvatar>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvatarList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BattleAvatar::class);
        $this->avatar_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleMonsterWave monster_wave_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMonsterWaveList()
    {
        return $this->monster_wave_list;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleMonsterWave monster_wave_list = 2;</code>
     * @param array<\BattleMonsterWave>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMonsterWaveList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BattleMonsterWave::class);
        $this->monster_wave_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleBuff buff_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBuffList()
    {
        return $this->buff_list;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleBuff buff_list = 3;</code>
     * @param array<\BattleBuff>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBuffList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BattleBuff::class);
        $this->buff_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 7;</code>
     * @return int
     */
    public function getWorldLevel()
    {
        return $this->world_level;
    }

    /**
     * Generated from protobuf field <code>uint32 world_level = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setWorldLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->world_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .JGOIHDOBEEK> PGKJOGNBOPO = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPGKJOGNBOPO()
    {
        return $this->PGKJOGNBOPO;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .JGOIHDOBEEK> PGKJOGNBOPO = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPGKJOGNBOPO($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \JGOIHDOBEEK::class);
        $this->PGKJOGNBOPO = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HMCNJLLHBLI LNEFJMMOMKB = 10;</code>
     * @return \HMCNJLLHBLI|null
     */
    public function getLNEFJMMOMKB()
    {
        return $this->LNEFJMMOMKB;
    }

    public function hasLNEFJMMOMKB()
    {
        return isset($this->LNEFJMMOMKB);
    }

    public function clearLNEFJMMOMKB()
    {
        unset($this->LNEFJMMOMKB);
    }

    /**
     * Generated from protobuf field <code>.HMCNJLLHBLI LNEFJMMOMKB = 10;</code>
     * @param \HMCNJLLHBLI $var
     * @return $this
     */
    public function setLNEFJMMOMKB($var)
    {
        GPBUtil::checkMessage($var, \HMCNJLLHBLI::class);
        $this->LNEFJMMOMKB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleAvatar JCFNBCABDNB = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJCFNBCABDNB()
    {
        return $this->JCFNBCABDNB;
    }

    /**
     * Generated from protobuf field <code>repeated .BattleAvatar JCFNBCABDNB = 11;</code>
     * @param array<\BattleAvatar>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJCFNBCABDNB($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BattleAvatar::class);
        $this->JCFNBCABDNB = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.EvolveBuildBattleInfo KAHOEKAEFHD = 12;</code>
     * @return \EvolveBuildBattleInfo|null
     */
    public function getKAHOEKAEFHD()
    {
        return $this->KAHOEKAEFHD;
    }

    public function hasKAHOEKAEFHD()
    {
        return isset($this->KAHOEKAEFHD);
    }

    public function clearKAHOEKAEFHD()
    {
        unset($this->KAHOEKAEFHD);
    }

    /**
     * Generated from protobuf field <code>.EvolveBuildBattleInfo KAHOEKAEFHD = 12;</code>
     * @param \EvolveBuildBattleInfo $var
     * @return $this
     */
    public function setKAHOEKAEFHD($var)
    {
        GPBUtil::checkMessage($var, \EvolveBuildBattleInfo::class);
        $this->KAHOEKAEFHD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KEJJGGCCGAN DHNDKIFPOLF = 13;</code>
     * @return \KEJJGGCCGAN|null
     */
    public function getDHNDKIFPOLF()
    {
        return $this->DHNDKIFPOLF;
    }

    public function hasDHNDKIFPOLF()
    {
        return isset($this->DHNDKIFPOLF);
    }

    public function clearDHNDKIFPOLF()
    {
        unset($this->DHNDKIFPOLF);
    }

    /**
     * Generated from protobuf field <code>.KEJJGGCCGAN DHNDKIFPOLF = 13;</code>
     * @param \KEJJGGCCGAN $var
     * @return $this
     */
    public function setDHNDKIFPOLF($var)
    {
        GPBUtil::checkMessage($var, \KEJJGGCCGAN::class);
        $this->DHNDKIFPOLF = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.BIMKJOHKBNO EPECBKPMBHE = 14;</code>
     * @return \BIMKJOHKBNO|null
     */
    public function getEPECBKPMBHE()
    {
        return $this->EPECBKPMBHE;
    }

    public function hasEPECBKPMBHE()
    {
        return isset($this->EPECBKPMBHE);
    }

    public function clearEPECBKPMBHE()
    {
        unset($this->EPECBKPMBHE);
    }

    /**
     * Generated from protobuf field <code>.BIMKJOHKBNO EPECBKPMBHE = 14;</code>
     * @param \BIMKJOHKBNO $var
     * @return $this
     */
    public function setEPECBKPMBHE($var)
    {
        GPBUtil::checkMessage($var, \BIMKJOHKBNO::class);
        $this->EPECBKPMBHE = $var;

        return $this;
    }

}

