<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LMHKCAHMNPE</code>
 */
class LMHKCAHMNPE extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 JCEAHHGJMKK = 2;</code>
     */
    protected $JCEAHHGJMKK = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 OPDEJDOOHOP = 10;</code>
     */
    private $OPDEJDOOHOP;
    /**
     * Generated from protobuf field <code>uint32 HPJAHKFGFKB = 14;</code>
     */
    protected $HPJAHKFGFKB = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $JCEAHHGJMKK
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $OPDEJDOOHOP
     *     @type int $HPJAHKFGFKB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 JCEAHHGJMKK = 2;</code>
     * @return int
     */
    public function getJCEAHHGJMKK()
    {
        return $this->JCEAHHGJMKK;
    }

    /**
     * Generated from protobuf field <code>uint32 JCEAHHGJMKK = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setJCEAHHGJMKK($var)
    {
        GPBUtil::checkUint32($var);
        $this->JCEAHHGJMKK = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 OPDEJDOOHOP = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOPDEJDOOHOP()
    {
        return $this->OPDEJDOOHOP;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 OPDEJDOOHOP = 10;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOPDEJDOOHOP($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->OPDEJDOOHOP = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 HPJAHKFGFKB = 14;</code>
     * @return int
     */
    public function getHPJAHKFGFKB()
    {
        return $this->HPJAHKFGFKB;
    }

    /**
     * Generated from protobuf field <code>uint32 HPJAHKFGFKB = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setHPJAHKFGFKB($var)
    {
        GPBUtil::checkUint32($var);
        $this->HPJAHKFGFKB = $var;

        return $this;
    }

}

