<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LOBBLPHFBEA</code>
 */
class LOBBLPHFBEA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.TrainPartySrc src = 2;</code>
     */
    protected $src = 0;
    protected $NKBFMHDHJGJ;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \BNKEFBKDJKP $jjnlkbfgicm
     *     @type \CKDHFNDDEAF $ppoffaffbde
     *     @type \KKBBOHLOGHN $mhpakbafjpb
     *     @type \DPOKFMOALKE $kdmhkmkkpin
     *     @type \GFPCBHIHDNN $johknhlbpop
     *     @type \FOHPEOLHHME $ifiiodejcbh
     *     @type \GDHBAIHFKBG $jkemhlopcao
     *     @type \FNBMAMMBKJJ $ajoonnaehme
     *     @type \NJOPBMFEEPJ $kokeloccepp
     *     @type \HOMBELLNGMA $jjfeabigbnc
     *     @type int $src
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.BNKEFBKDJKP jjnlkbfgicm = 164;</code>
     * @return \BNKEFBKDJKP|null
     */
    public function getJjnlkbfgicm()
    {
        return $this->readOneof(164);
    }

    public function hasJjnlkbfgicm()
    {
        return $this->hasOneof(164);
    }

    /**
     * Generated from protobuf field <code>.BNKEFBKDJKP jjnlkbfgicm = 164;</code>
     * @param \BNKEFBKDJKP $var
     * @return $this
     */
    public function setJjnlkbfgicm($var)
    {
        GPBUtil::checkMessage($var, \BNKEFBKDJKP::class);
        $this->writeOneof(164, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CKDHFNDDEAF ppoffaffbde = 463;</code>
     * @return \CKDHFNDDEAF|null
     */
    public function getPpoffaffbde()
    {
        return $this->readOneof(463);
    }

    public function hasPpoffaffbde()
    {
        return $this->hasOneof(463);
    }

    /**
     * Generated from protobuf field <code>.CKDHFNDDEAF ppoffaffbde = 463;</code>
     * @param \CKDHFNDDEAF $var
     * @return $this
     */
    public function setPpoffaffbde($var)
    {
        GPBUtil::checkMessage($var, \CKDHFNDDEAF::class);
        $this->writeOneof(463, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KKBBOHLOGHN mhpakbafjpb = 140;</code>
     * @return \KKBBOHLOGHN|null
     */
    public function getMhpakbafjpb()
    {
        return $this->readOneof(140);
    }

    public function hasMhpakbafjpb()
    {
        return $this->hasOneof(140);
    }

    /**
     * Generated from protobuf field <code>.KKBBOHLOGHN mhpakbafjpb = 140;</code>
     * @param \KKBBOHLOGHN $var
     * @return $this
     */
    public function setMhpakbafjpb($var)
    {
        GPBUtil::checkMessage($var, \KKBBOHLOGHN::class);
        $this->writeOneof(140, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DPOKFMOALKE kdmhkmkkpin = 1135;</code>
     * @return \DPOKFMOALKE|null
     */
    public function getKdmhkmkkpin()
    {
        return $this->readOneof(1135);
    }

    public function hasKdmhkmkkpin()
    {
        return $this->hasOneof(1135);
    }

    /**
     * Generated from protobuf field <code>.DPOKFMOALKE kdmhkmkkpin = 1135;</code>
     * @param \DPOKFMOALKE $var
     * @return $this
     */
    public function setKdmhkmkkpin($var)
    {
        GPBUtil::checkMessage($var, \DPOKFMOALKE::class);
        $this->writeOneof(1135, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GFPCBHIHDNN johknhlbpop = 784;</code>
     * @return \GFPCBHIHDNN|null
     */
    public function getJohknhlbpop()
    {
        return $this->readOneof(784);
    }

    public function hasJohknhlbpop()
    {
        return $this->hasOneof(784);
    }

    /**
     * Generated from protobuf field <code>.GFPCBHIHDNN johknhlbpop = 784;</code>
     * @param \GFPCBHIHDNN $var
     * @return $this
     */
    public function setJohknhlbpop($var)
    {
        GPBUtil::checkMessage($var, \GFPCBHIHDNN::class);
        $this->writeOneof(784, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FOHPEOLHHME ifiiodejcbh = 1913;</code>
     * @return \FOHPEOLHHME|null
     */
    public function getIfiiodejcbh()
    {
        return $this->readOneof(1913);
    }

    public function hasIfiiodejcbh()
    {
        return $this->hasOneof(1913);
    }

    /**
     * Generated from protobuf field <code>.FOHPEOLHHME ifiiodejcbh = 1913;</code>
     * @param \FOHPEOLHHME $var
     * @return $this
     */
    public function setIfiiodejcbh($var)
    {
        GPBUtil::checkMessage($var, \FOHPEOLHHME::class);
        $this->writeOneof(1913, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GDHBAIHFKBG jkemhlopcao = 44;</code>
     * @return \GDHBAIHFKBG|null
     */
    public function getJkemhlopcao()
    {
        return $this->readOneof(44);
    }

    public function hasJkemhlopcao()
    {
        return $this->hasOneof(44);
    }

    /**
     * Generated from protobuf field <code>.GDHBAIHFKBG jkemhlopcao = 44;</code>
     * @param \GDHBAIHFKBG $var
     * @return $this
     */
    public function setJkemhlopcao($var)
    {
        GPBUtil::checkMessage($var, \GDHBAIHFKBG::class);
        $this->writeOneof(44, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FNBMAMMBKJJ ajoonnaehme = 1535;</code>
     * @return \FNBMAMMBKJJ|null
     */
    public function getAjoonnaehme()
    {
        return $this->readOneof(1535);
    }

    public function hasAjoonnaehme()
    {
        return $this->hasOneof(1535);
    }

    /**
     * Generated from protobuf field <code>.FNBMAMMBKJJ ajoonnaehme = 1535;</code>
     * @param \FNBMAMMBKJJ $var
     * @return $this
     */
    public function setAjoonnaehme($var)
    {
        GPBUtil::checkMessage($var, \FNBMAMMBKJJ::class);
        $this->writeOneof(1535, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NJOPBMFEEPJ kokeloccepp = 492;</code>
     * @return \NJOPBMFEEPJ|null
     */
    public function getKokeloccepp()
    {
        return $this->readOneof(492);
    }

    public function hasKokeloccepp()
    {
        return $this->hasOneof(492);
    }

    /**
     * Generated from protobuf field <code>.NJOPBMFEEPJ kokeloccepp = 492;</code>
     * @param \NJOPBMFEEPJ $var
     * @return $this
     */
    public function setKokeloccepp($var)
    {
        GPBUtil::checkMessage($var, \NJOPBMFEEPJ::class);
        $this->writeOneof(492, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HOMBELLNGMA jjfeabigbnc = 337;</code>
     * @return \HOMBELLNGMA|null
     */
    public function getJjfeabigbnc()
    {
        return $this->readOneof(337);
    }

    public function hasJjfeabigbnc()
    {
        return $this->hasOneof(337);
    }

    /**
     * Generated from protobuf field <code>.HOMBELLNGMA jjfeabigbnc = 337;</code>
     * @param \HOMBELLNGMA $var
     * @return $this
     */
    public function setJjfeabigbnc($var)
    {
        GPBUtil::checkMessage($var, \HOMBELLNGMA::class);
        $this->writeOneof(337, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TrainPartySrc src = 2;</code>
     * @return int
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Generated from protobuf field <code>.TrainPartySrc src = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSrc($var)
    {
        GPBUtil::checkEnum($var, \TrainPartySrc::class);
        $this->src = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getNKBFMHDHJGJ()
    {
        return $this->whichOneof("NKBFMHDHJGJ");
    }

}

