<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MainMission</code>
 */
class MainMission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 11;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.MissionStatus status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>repeated .MissionCustomValue custom_value_list = 3;</code>
     */
    private $custom_value_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $status
     *     @type array<\MissionCustomValue>|\Google\Protobuf\Internal\RepeatedField $custom_value_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 11;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MissionStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.MissionStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \MissionStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MissionCustomValue custom_value_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomValueList()
    {
        return $this->custom_value_list;
    }

    /**
     * Generated from protobuf field <code>repeated .MissionCustomValue custom_value_list = 3;</code>
     * @param array<\MissionCustomValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomValueList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MissionCustomValue::class);
        $this->custom_value_list = $arr;

        return $this;
    }

}

