<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MakeMissionDrinkScRsp (6990)
 *
 * Generated from protobuf message <code>MakeMissionDrinkScRsp</code>
 */
class MakeMissionDrinkScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>bool IsSucc = 6;</code>
     */
    protected $IsSucc = false;
    /**
     * Generated from protobuf field <code>bool IsSave = 10;</code>
     */
    protected $IsSave = false;
    /**
     * Generated from protobuf field <code>.HHIINBEPCPI CustomDrink = 1;</code>
     */
    protected $CustomDrink = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type bool $IsSucc
     *     @type bool $IsSave
     *     @type \HHIINBEPCPI $CustomDrink
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsSucc = 6;</code>
     * @return bool
     */
    public function getIsSucc()
    {
        return $this->IsSucc;
    }

    /**
     * Generated from protobuf field <code>bool IsSucc = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSucc($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSucc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsSave = 10;</code>
     * @return bool
     */
    public function getIsSave()
    {
        return $this->IsSave;
    }

    /**
     * Generated from protobuf field <code>bool IsSave = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSave($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSave = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HHIINBEPCPI CustomDrink = 1;</code>
     * @return \HHIINBEPCPI|null
     */
    public function getCustomDrink()
    {
        return $this->CustomDrink;
    }

    public function hasCustomDrink()
    {
        return isset($this->CustomDrink);
    }

    public function clearCustomDrink()
    {
        unset($this->CustomDrink);
    }

    /**
     * Generated from protobuf field <code>.HHIINBEPCPI CustomDrink = 1;</code>
     * @param \HHIINBEPCPI $var
     * @return $this
     */
    public function setCustomDrink($var)
    {
        GPBUtil::checkMessage($var, \HHIINBEPCPI::class);
        $this->CustomDrink = $var;

        return $this;
    }

}

