<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * FOGDLPFBEKC (3934)
 *
 * Generated from protobuf message <code>MarkChatEmojiCsReq</code>
 */
class MarkChatEmojiCsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_remove_id = 12;</code>
     */
    protected $is_remove_id = false;
    /**
     * Generated from protobuf field <code>uint32 extra_id = 11;</code>
     */
    protected $extra_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_remove_id
     *     @type int $extra_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_remove_id = 12;</code>
     * @return bool
     */
    public function getIsRemoveId()
    {
        return $this->is_remove_id;
    }

    /**
     * Generated from protobuf field <code>bool is_remove_id = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRemoveId($var)
    {
        GPBUtil::checkBool($var);
        $this->is_remove_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 extra_id = 11;</code>
     * @return int
     */
    public function getExtraId()
    {
        return $this->extra_id;
    }

    /**
     * Generated from protobuf field <code>uint32 extra_id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setExtraId($var)
    {
        GPBUtil::checkUint32($var);
        $this->extra_id = $var;

        return $this;
    }

}

