<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MENNDCCODOM</code>
 */
class MENNDCCODOM extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 NEIOBABBGLH = 4;</code>
     */
    protected $NEIOBABBGLH = 0;
    /**
     * Generated from protobuf field <code>uint32 value = 15;</code>
     */
    protected $value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $NEIOBABBGLH
     *     @type int $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 NEIOBABBGLH = 4;</code>
     * @return int
     */
    public function getNEIOBABBGLH()
    {
        return $this->NEIOBABBGLH;
    }

    /**
     * Generated from protobuf field <code>uint32 NEIOBABBGLH = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNEIOBABBGLH($var)
    {
        GPBUtil::checkUint32($var);
        $this->NEIOBABBGLH = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 15;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->value = $var;

        return $this;
    }

}

