<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MFOLMDABICO</code>
 */
class MFOLMDABICO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 apapipmoggc = 9;</code>
     */
    protected $apapipmoggc = 0;
    /**
     * Generated from protobuf field <code>uint32 cdcnhleaale = 6;</code>
     */
    protected $cdcnhleaale = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $apapipmoggc
     *     @type int $cdcnhleaale
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 apapipmoggc = 9;</code>
     * @return int
     */
    public function getApapipmoggc()
    {
        return $this->apapipmoggc;
    }

    /**
     * Generated from protobuf field <code>uint32 apapipmoggc = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setApapipmoggc($var)
    {
        GPBUtil::checkUint32($var);
        $this->apapipmoggc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cdcnhleaale = 6;</code>
     * @return int
     */
    public function getCdcnhleaale()
    {
        return $this->cdcnhleaale;
    }

    /**
     * Generated from protobuf field <code>uint32 cdcnhleaale = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCdcnhleaale($var)
    {
        GPBUtil::checkUint32($var);
        $this->cdcnhleaale = $var;

        return $this;
    }

}

