<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * fake
 *
 * Generated from protobuf message <code>MLPJEPDPCLK</code>
 */
class MLPJEPDPCLK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 monster_list = 1;</code>
     */
    protected $monster_list = 0;
    /**
     * Generated from protobuf field <code>uint32 max_hp = 2;</code>
     */
    protected $max_hp = 0;
    /**
     * Generated from protobuf field <code>uint32 HCBLBJJAKHJ = 3;</code>
     */
    protected $HCBLBJJAKHJ = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $monster_list
     *     @type int $max_hp
     *     @type int $HCBLBJJAKHJ
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 monster_list = 1;</code>
     * @return int
     */
    public function getMonsterList()
    {
        return $this->monster_list;
    }

    /**
     * Generated from protobuf field <code>uint32 monster_list = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMonsterList($var)
    {
        GPBUtil::checkUint32($var);
        $this->monster_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_hp = 2;</code>
     * @return int
     */
    public function getMaxHp()
    {
        return $this->max_hp;
    }

    /**
     * Generated from protobuf field <code>uint32 max_hp = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxHp($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_hp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 HCBLBJJAKHJ = 3;</code>
     * @return int
     */
    public function getHCBLBJJAKHJ()
    {
        return $this->HCBLBJJAKHJ;
    }

    /**
     * Generated from protobuf field <code>uint32 HCBLBJJAKHJ = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHCBLBJJAKHJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->HCBLBJJAKHJ = $var;

        return $this;
    }

}

