<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MPKGJGHAJMH</code>
 */
class MPKGJGHAJMH extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 PDHDKBJJOFJ = 5;</code>
     */
    protected $PDHDKBJJOFJ = 0;
    /**
     * Generated from protobuf field <code>repeated .KJJHDCBAGMK GLAFMDCKCLI = 8;</code>
     */
    private $GLAFMDCKCLI;
    /**
     * Generated from protobuf field <code>.NFIHMNFEGKO NFLBAIBNMIG = 1;</code>
     */
    protected $NFLBAIBNMIG = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $PDHDKBJJOFJ
     *     @type array<\KJJHDCBAGMK>|\Google\Protobuf\Internal\RepeatedField $GLAFMDCKCLI
     *     @type int $NFLBAIBNMIG
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 PDHDKBJJOFJ = 5;</code>
     * @return int
     */
    public function getPDHDKBJJOFJ()
    {
        return $this->PDHDKBJJOFJ;
    }

    /**
     * Generated from protobuf field <code>uint32 PDHDKBJJOFJ = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPDHDKBJJOFJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->PDHDKBJJOFJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .KJJHDCBAGMK GLAFMDCKCLI = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGLAFMDCKCLI()
    {
        return $this->GLAFMDCKCLI;
    }

    /**
     * Generated from protobuf field <code>repeated .KJJHDCBAGMK GLAFMDCKCLI = 8;</code>
     * @param array<\KJJHDCBAGMK>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGLAFMDCKCLI($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KJJHDCBAGMK::class);
        $this->GLAFMDCKCLI = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NFIHMNFEGKO NFLBAIBNMIG = 1;</code>
     * @return int
     */
    public function getNFLBAIBNMIG()
    {
        return $this->NFLBAIBNMIG;
    }

    /**
     * Generated from protobuf field <code>.NFIHMNFEGKO NFLBAIBNMIG = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNFLBAIBNMIG($var)
    {
        GPBUtil::checkEnum($var, \NFIHMNFEGKO::class);
        $this->NFLBAIBNMIG = $var;

        return $this;
    }

}

