<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NEGIFANELHM</code>
 */
class NEGIFANELHM extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 BPFBJKCFLKH = 6;</code>
     */
    protected $BPFBJKCFLKH = 0;
    /**
     * Generated from protobuf field <code>.FCCFGOINNHB status = 12;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 HHBNIFIJLKJ = 13;</code>
     */
    protected $HHBNIFIJLKJ = 0;
    /**
     * Generated from protobuf field <code>uint32 HGMFEGGJEFB = 3;</code>
     */
    protected $HGMFEGGJEFB = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $BPFBJKCFLKH
     *     @type int $status
     *     @type int $HHBNIFIJLKJ
     *     @type int $HGMFEGGJEFB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 BPFBJKCFLKH = 6;</code>
     * @return int
     */
    public function getBPFBJKCFLKH()
    {
        return $this->BPFBJKCFLKH;
    }

    /**
     * Generated from protobuf field <code>uint32 BPFBJKCFLKH = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setBPFBJKCFLKH($var)
    {
        GPBUtil::checkUint32($var);
        $this->BPFBJKCFLKH = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FCCFGOINNHB status = 12;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.FCCFGOINNHB status = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \FCCFGOINNHB::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 HHBNIFIJLKJ = 13;</code>
     * @return int
     */
    public function getHHBNIFIJLKJ()
    {
        return $this->HHBNIFIJLKJ;
    }

    /**
     * Generated from protobuf field <code>uint32 HHBNIFIJLKJ = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setHHBNIFIJLKJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->HHBNIFIJLKJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 HGMFEGGJEFB = 3;</code>
     * @return int
     */
    public function getHGMFEGGJEFB()
    {
        return $this->HGMFEGGJEFB;
    }

    /**
     * Generated from protobuf field <code>uint32 HGMFEGGJEFB = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHGMFEGGJEFB($var)
    {
        GPBUtil::checkUint32($var);
        $this->HGMFEGGJEFB = $var;

        return $this;
    }

}

