<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NGHOHLDBCHP</code>
 */
class NGHOHLDBCHP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ibkhmiclebj = 5;</code>
     */
    protected $ibkhmiclebj = 0;
    /**
     * Generated from protobuf field <code>uint32 cilhldkohhp = 9;</code>
     */
    protected $cilhldkohhp = 0;
    /**
     * Generated from protobuf field <code>.ItemList item_list = 8;</code>
     */
    protected $item_list = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ibkhmiclebj
     *     @type int $cilhldkohhp
     *     @type \ItemList $item_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ibkhmiclebj = 5;</code>
     * @return int
     */
    public function getIbkhmiclebj()
    {
        return $this->ibkhmiclebj;
    }

    /**
     * Generated from protobuf field <code>uint32 ibkhmiclebj = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIbkhmiclebj($var)
    {
        GPBUtil::checkUint32($var);
        $this->ibkhmiclebj = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cilhldkohhp = 9;</code>
     * @return int
     */
    public function getCilhldkohhp()
    {
        return $this->cilhldkohhp;
    }

    /**
     * Generated from protobuf field <code>uint32 cilhldkohhp = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCilhldkohhp($var)
    {
        GPBUtil::checkUint32($var);
        $this->cilhldkohhp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemList item_list = 8;</code>
     * @return \ItemList|null
     */
    public function getItemList()
    {
        return $this->item_list;
    }

    public function hasItemList()
    {
        return isset($this->item_list);
    }

    public function clearItemList()
    {
        unset($this->item_list);
    }

    /**
     * Generated from protobuf field <code>.ItemList item_list = 8;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setItemList($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->item_list = $var;

        return $this;
    }

}

