<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NJICCNHCMDK</code>
 */
class NJICCNHCMDK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 nkgnmapebbe = 14;</code>
     */
    private $nkgnmapebbe;
    /**
     * Generated from protobuf field <code>.EAPPPCLJBCJ foobjefjagg = 10;</code>
     */
    protected $foobjefjagg = null;
    /**
     * Generated from protobuf field <code>repeated .AFCBFFDAHEB rogue_magic_unit_info_list = 11;</code>
     */
    private $rogue_magic_unit_info_list;
    /**
     * Generated from protobuf field <code>repeated .JBGNJNJEOIL ecapbmomfbh = 5;</code>
     */
    private $ecapbmomfbh;
    /**
     * Generated from protobuf field <code>repeated .ABDHKCOFEEC afbbgjiajne = 9;</code>
     */
    private $afbbgjiajne;
    /**
     * Generated from protobuf field <code>repeated .ELGAMGEDGOM cgnfacmppco = 8;</code>
     */
    private $cgnfacmppco;
    /**
     * Generated from protobuf field <code>.HGDOLNGHMIG story_info = 3;</code>
     */
    protected $story_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $nkgnmapebbe
     *     @type \EAPPPCLJBCJ $foobjefjagg
     *     @type array<\AFCBFFDAHEB>|\Google\Protobuf\Internal\RepeatedField $rogue_magic_unit_info_list
     *     @type array<\JBGNJNJEOIL>|\Google\Protobuf\Internal\RepeatedField $ecapbmomfbh
     *     @type array<\ABDHKCOFEEC>|\Google\Protobuf\Internal\RepeatedField $afbbgjiajne
     *     @type array<\ELGAMGEDGOM>|\Google\Protobuf\Internal\RepeatedField $cgnfacmppco
     *     @type \HGDOLNGHMIG $story_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 nkgnmapebbe = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNkgnmapebbe()
    {
        return $this->nkgnmapebbe;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 nkgnmapebbe = 14;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNkgnmapebbe($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->nkgnmapebbe = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.EAPPPCLJBCJ foobjefjagg = 10;</code>
     * @return \EAPPPCLJBCJ|null
     */
    public function getFoobjefjagg()
    {
        return $this->foobjefjagg;
    }

    public function hasFoobjefjagg()
    {
        return isset($this->foobjefjagg);
    }

    public function clearFoobjefjagg()
    {
        unset($this->foobjefjagg);
    }

    /**
     * Generated from protobuf field <code>.EAPPPCLJBCJ foobjefjagg = 10;</code>
     * @param \EAPPPCLJBCJ $var
     * @return $this
     */
    public function setFoobjefjagg($var)
    {
        GPBUtil::checkMessage($var, \EAPPPCLJBCJ::class);
        $this->foobjefjagg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AFCBFFDAHEB rogue_magic_unit_info_list = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRogueMagicUnitInfoList()
    {
        return $this->rogue_magic_unit_info_list;
    }

    /**
     * Generated from protobuf field <code>repeated .AFCBFFDAHEB rogue_magic_unit_info_list = 11;</code>
     * @param array<\AFCBFFDAHEB>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRogueMagicUnitInfoList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AFCBFFDAHEB::class);
        $this->rogue_magic_unit_info_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .JBGNJNJEOIL ecapbmomfbh = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEcapbmomfbh()
    {
        return $this->ecapbmomfbh;
    }

    /**
     * Generated from protobuf field <code>repeated .JBGNJNJEOIL ecapbmomfbh = 5;</code>
     * @param array<\JBGNJNJEOIL>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEcapbmomfbh($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \JBGNJNJEOIL::class);
        $this->ecapbmomfbh = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ABDHKCOFEEC afbbgjiajne = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAfbbgjiajne()
    {
        return $this->afbbgjiajne;
    }

    /**
     * Generated from protobuf field <code>repeated .ABDHKCOFEEC afbbgjiajne = 9;</code>
     * @param array<\ABDHKCOFEEC>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAfbbgjiajne($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ABDHKCOFEEC::class);
        $this->afbbgjiajne = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ELGAMGEDGOM cgnfacmppco = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCgnfacmppco()
    {
        return $this->cgnfacmppco;
    }

    /**
     * Generated from protobuf field <code>repeated .ELGAMGEDGOM cgnfacmppco = 8;</code>
     * @param array<\ELGAMGEDGOM>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCgnfacmppco($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ELGAMGEDGOM::class);
        $this->cgnfacmppco = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HGDOLNGHMIG story_info = 3;</code>
     * @return \HGDOLNGHMIG|null
     */
    public function getStoryInfo()
    {
        return $this->story_info;
    }

    public function hasStoryInfo()
    {
        return isset($this->story_info);
    }

    public function clearStoryInfo()
    {
        unset($this->story_info);
    }

    /**
     * Generated from protobuf field <code>.HGDOLNGHMIG story_info = 3;</code>
     * @param \HGDOLNGHMIG $var
     * @return $this
     */
    public function setStoryInfo($var)
    {
        GPBUtil::checkMessage($var, \HGDOLNGHMIG::class);
        $this->story_info = $var;

        return $this;
    }

}

