<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OJGDHAFNDNA</code>
 */
class OJGDHAFNDNA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 MAPLEIJNLMF = 2;</code>
     */
    protected $MAPLEIJNLMF = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 GEPFLMFCHBI = 6;</code>
     */
    private $GEPFLMFCHBI;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $MAPLEIJNLMF
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $GEPFLMFCHBI
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 MAPLEIJNLMF = 2;</code>
     * @return int
     */
    public function getMAPLEIJNLMF()
    {
        return $this->MAPLEIJNLMF;
    }

    /**
     * Generated from protobuf field <code>uint32 MAPLEIJNLMF = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMAPLEIJNLMF($var)
    {
        GPBUtil::checkUint32($var);
        $this->MAPLEIJNLMF = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 GEPFLMFCHBI = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGEPFLMFCHBI()
    {
        return $this->GEPFLMFCHBI;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 GEPFLMFCHBI = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGEPFLMFCHBI($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->GEPFLMFCHBI = $arr;

        return $this;
    }

}

