<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OMOCAFMFDKE</code>
 */
class OMOCAFMFDKE extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.FPPNOEJJNHA KKFKECEMFEB = 6;</code>
     */
    protected $KKFKECEMFEB = 0;
    /**
     * Generated from protobuf field <code>uint32 plane_id = 5;</code>
     */
    protected $plane_id = 0;
    /**
     * Generated from protobuf field <code>.AvatarType avatar_type = 4;</code>
     */
    protected $avatar_type = 0;
    /**
     * Generated from protobuf field <code>uint32 index = 12;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>uint32 base_avatar_id = 7;</code>
     */
    protected $base_avatar_id = 0;
    /**
     * Generated from protobuf field <code>bool EDHDMHPBHCH = 11;</code>
     */
    protected $EDHDMHPBHCH = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $KKFKECEMFEB
     *     @type int $plane_id
     *     @type int $avatar_type
     *     @type int $index
     *     @type int $base_avatar_id
     *     @type bool $EDHDMHPBHCH
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.FPPNOEJJNHA KKFKECEMFEB = 6;</code>
     * @return int
     */
    public function getKKFKECEMFEB()
    {
        return $this->KKFKECEMFEB;
    }

    /**
     * Generated from protobuf field <code>.FPPNOEJJNHA KKFKECEMFEB = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setKKFKECEMFEB($var)
    {
        GPBUtil::checkEnum($var, \FPPNOEJJNHA::class);
        $this->KKFKECEMFEB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 plane_id = 5;</code>
     * @return int
     */
    public function getPlaneId()
    {
        return $this->plane_id;
    }

    /**
     * Generated from protobuf field <code>uint32 plane_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPlaneId($var)
    {
        GPBUtil::checkUint32($var);
        $this->plane_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AvatarType avatar_type = 4;</code>
     * @return int
     */
    public function getAvatarType()
    {
        return $this->avatar_type;
    }

    /**
     * Generated from protobuf field <code>.AvatarType avatar_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAvatarType($var)
    {
        GPBUtil::checkEnum($var, \AvatarType::class);
        $this->avatar_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 12;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 base_avatar_id = 7;</code>
     * @return int
     */
    public function getBaseAvatarId()
    {
        return $this->base_avatar_id;
    }

    /**
     * Generated from protobuf field <code>uint32 base_avatar_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setBaseAvatarId($var)
    {
        GPBUtil::checkUint32($var);
        $this->base_avatar_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool EDHDMHPBHCH = 11;</code>
     * @return bool
     */
    public function getEDHDMHPBHCH()
    {
        return $this->EDHDMHPBHCH;
    }

    /**
     * Generated from protobuf field <code>bool EDHDMHPBHCH = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setEDHDMHPBHCH($var)
    {
        GPBUtil::checkBool($var);
        $this->EDHDMHPBHCH = $var;

        return $this;
    }

}

