<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * INEBGMGFGOF (1872)
 *
 * Generated from protobuf message <code>OpenRogueChestScRsp</code>
 */
class OpenRogueChestScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ItemList reward = 7;</code>
     */
    protected $reward = null;
    /**
     * Generated from protobuf field <code>.ItemList ieinoefbllp = 14;</code>
     */
    protected $ieinoefbllp = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ItemList $reward
     *     @type \ItemList $ieinoefbllp
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 7;</code>
     * @return \ItemList|null
     */
    public function getReward()
    {
        return $this->reward;
    }

    public function hasReward()
    {
        return isset($this->reward);
    }

    public function clearReward()
    {
        unset($this->reward);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 7;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemList ieinoefbllp = 14;</code>
     * @return \ItemList|null
     */
    public function getIeinoefbllp()
    {
        return $this->ieinoefbllp;
    }

    public function hasIeinoefbllp()
    {
        return isset($this->ieinoefbllp);
    }

    public function clearIeinoefbllp()
    {
        unset($this->ieinoefbllp);
    }

    /**
     * Generated from protobuf field <code>.ItemList ieinoefbllp = 14;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setIeinoefbllp($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->ieinoefbllp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

