<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PCDJAEFBHHJ</code>
 */
class PCDJAEFBHHJ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.FeatureSwitchType MKGHPNAOCFB = 7;</code>
     */
    protected $MKGHPNAOCFB = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $MKGHPNAOCFB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.FeatureSwitchType MKGHPNAOCFB = 7;</code>
     * @return int
     */
    public function getMKGHPNAOCFB()
    {
        return $this->MKGHPNAOCFB;
    }

    /**
     * Generated from protobuf field <code>.FeatureSwitchType MKGHPNAOCFB = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMKGHPNAOCFB($var)
    {
        GPBUtil::checkEnum($var, \FeatureSwitchType::class);
        $this->MKGHPNAOCFB = $var;

        return $this;
    }

}

