<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PDCBFEBJEDH</code>
 */
class PDCBFEBJEDH extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 HLCDJBLKODE = 9;</code>
     */
    protected $HLCDJBLKODE = 0;
    /**
     * Generated from protobuf field <code>uint32 ILIFHHJFMIH = 13;</code>
     */
    protected $ILIFHHJFMIH = 0;
    /**
     * Generated from protobuf field <code>.LGHCCONCDND IHDHILFGKPC = 199;</code>
     */
    protected $IHDHILFGKPC = null;
    /**
     * Generated from protobuf field <code>.LACFFODHCBM HFCHCPJDBNG = 1020;</code>
     */
    protected $HFCHCPJDBNG = null;
    /**
     * Generated from protobuf field <code>.IBKIPHGHHFC OLPJNEOLJIM = 1142;</code>
     */
    protected $OLPJNEOLJIM = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $HLCDJBLKODE
     *     @type int $ILIFHHJFMIH
     *     @type \LGHCCONCDND $IHDHILFGKPC
     *     @type \LACFFODHCBM $HFCHCPJDBNG
     *     @type \IBKIPHGHHFC $OLPJNEOLJIM
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 HLCDJBLKODE = 9;</code>
     * @return int
     */
    public function getHLCDJBLKODE()
    {
        return $this->HLCDJBLKODE;
    }

    /**
     * Generated from protobuf field <code>uint32 HLCDJBLKODE = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setHLCDJBLKODE($var)
    {
        GPBUtil::checkUint32($var);
        $this->HLCDJBLKODE = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ILIFHHJFMIH = 13;</code>
     * @return int
     */
    public function getILIFHHJFMIH()
    {
        return $this->ILIFHHJFMIH;
    }

    /**
     * Generated from protobuf field <code>uint32 ILIFHHJFMIH = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setILIFHHJFMIH($var)
    {
        GPBUtil::checkUint32($var);
        $this->ILIFHHJFMIH = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LGHCCONCDND IHDHILFGKPC = 199;</code>
     * @return \LGHCCONCDND|null
     */
    public function getIHDHILFGKPC()
    {
        return $this->IHDHILFGKPC;
    }

    public function hasIHDHILFGKPC()
    {
        return isset($this->IHDHILFGKPC);
    }

    public function clearIHDHILFGKPC()
    {
        unset($this->IHDHILFGKPC);
    }

    /**
     * Generated from protobuf field <code>.LGHCCONCDND IHDHILFGKPC = 199;</code>
     * @param \LGHCCONCDND $var
     * @return $this
     */
    public function setIHDHILFGKPC($var)
    {
        GPBUtil::checkMessage($var, \LGHCCONCDND::class);
        $this->IHDHILFGKPC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LACFFODHCBM HFCHCPJDBNG = 1020;</code>
     * @return \LACFFODHCBM|null
     */
    public function getHFCHCPJDBNG()
    {
        return $this->HFCHCPJDBNG;
    }

    public function hasHFCHCPJDBNG()
    {
        return isset($this->HFCHCPJDBNG);
    }

    public function clearHFCHCPJDBNG()
    {
        unset($this->HFCHCPJDBNG);
    }

    /**
     * Generated from protobuf field <code>.LACFFODHCBM HFCHCPJDBNG = 1020;</code>
     * @param \LACFFODHCBM $var
     * @return $this
     */
    public function setHFCHCPJDBNG($var)
    {
        GPBUtil::checkMessage($var, \LACFFODHCBM::class);
        $this->HFCHCPJDBNG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IBKIPHGHHFC OLPJNEOLJIM = 1142;</code>
     * @return \IBKIPHGHHFC|null
     */
    public function getOLPJNEOLJIM()
    {
        return $this->OLPJNEOLJIM;
    }

    public function hasOLPJNEOLJIM()
    {
        return isset($this->OLPJNEOLJIM);
    }

    public function clearOLPJNEOLJIM()
    {
        unset($this->OLPJNEOLJIM);
    }

    /**
     * Generated from protobuf field <code>.IBKIPHGHHFC OLPJNEOLJIM = 1142;</code>
     * @param \IBKIPHGHHFC $var
     * @return $this
     */
    public function setOLPJNEOLJIM($var)
    {
        GPBUtil::checkMessage($var, \IBKIPHGHHFC::class);
        $this->OLPJNEOLJIM = $var;

        return $this;
    }

}

