<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PFGJIPKOOPJ</code>
 */
class PFGJIPKOOPJ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 PENJHINGIGC = 11;</code>
     */
    protected $PENJHINGIGC = 0;
    /**
     * Generated from protobuf field <code>uint32 FHBPLGNBCBG = 12;</code>
     */
    protected $FHBPLGNBCBG = 0;
    /**
     * Generated from protobuf field <code>uint32 MKPFFLFMIHJ = 4;</code>
     */
    protected $MKPFFLFMIHJ = 0;
    /**
     * Generated from protobuf field <code>repeated .EGHKPPGADBN IKIMFHFLDNN = 6;</code>
     */
    private $IKIMFHFLDNN;
    /**
     * Generated from protobuf field <code>uint32 DCBAGJMCHEB = 5;</code>
     */
    protected $DCBAGJMCHEB = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $PENJHINGIGC
     *     @type int $FHBPLGNBCBG
     *     @type int $MKPFFLFMIHJ
     *     @type array<\EGHKPPGADBN>|\Google\Protobuf\Internal\RepeatedField $IKIMFHFLDNN
     *     @type int $DCBAGJMCHEB
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 PENJHINGIGC = 11;</code>
     * @return int
     */
    public function getPENJHINGIGC()
    {
        return $this->PENJHINGIGC;
    }

    /**
     * Generated from protobuf field <code>uint32 PENJHINGIGC = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPENJHINGIGC($var)
    {
        GPBUtil::checkUint32($var);
        $this->PENJHINGIGC = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 FHBPLGNBCBG = 12;</code>
     * @return int
     */
    public function getFHBPLGNBCBG()
    {
        return $this->FHBPLGNBCBG;
    }

    /**
     * Generated from protobuf field <code>uint32 FHBPLGNBCBG = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setFHBPLGNBCBG($var)
    {
        GPBUtil::checkUint32($var);
        $this->FHBPLGNBCBG = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 MKPFFLFMIHJ = 4;</code>
     * @return int
     */
    public function getMKPFFLFMIHJ()
    {
        return $this->MKPFFLFMIHJ;
    }

    /**
     * Generated from protobuf field <code>uint32 MKPFFLFMIHJ = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMKPFFLFMIHJ($var)
    {
        GPBUtil::checkUint32($var);
        $this->MKPFFLFMIHJ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .EGHKPPGADBN IKIMFHFLDNN = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIKIMFHFLDNN()
    {
        return $this->IKIMFHFLDNN;
    }

    /**
     * Generated from protobuf field <code>repeated .EGHKPPGADBN IKIMFHFLDNN = 6;</code>
     * @param array<\EGHKPPGADBN>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIKIMFHFLDNN($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \EGHKPPGADBN::class);
        $this->IKIMFHFLDNN = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 DCBAGJMCHEB = 5;</code>
     * @return int
     */
    public function getDCBAGJMCHEB()
    {
        return $this->DCBAGJMCHEB;
    }

    /**
     * Generated from protobuf field <code>uint32 DCBAGJMCHEB = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDCBAGJMCHEB($var)
    {
        GPBUtil::checkUint32($var);
        $this->DCBAGJMCHEB = $var;

        return $this;
    }

}

