<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PGHLCGOPCDJ</code>
 */
class PGHLCGOPCDJ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string NLJCBFBNGOD = 12;</code>
     */
    protected $NLJCBFBNGOD = '';
    /**
     * Generated from protobuf field <code>uint32 PDOMAMNJNIF = 15;</code>
     */
    protected $PDOMAMNJNIF = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 CBPBAHEADKJ = 13;</code>
     */
    private $CBPBAHEADKJ;
    /**
     * Generated from protobuf field <code>.IPDPIAGBMNO HAJAODDHKCN = 9;</code>
     */
    protected $HAJAODDHKCN = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $NLJCBFBNGOD
     *     @type int $PDOMAMNJNIF
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $CBPBAHEADKJ
     *     @type \IPDPIAGBMNO $HAJAODDHKCN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string NLJCBFBNGOD = 12;</code>
     * @return string
     */
    public function getNLJCBFBNGOD()
    {
        return $this->NLJCBFBNGOD;
    }

    /**
     * Generated from protobuf field <code>string NLJCBFBNGOD = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setNLJCBFBNGOD($var)
    {
        GPBUtil::checkString($var, True);
        $this->NLJCBFBNGOD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 PDOMAMNJNIF = 15;</code>
     * @return int
     */
    public function getPDOMAMNJNIF()
    {
        return $this->PDOMAMNJNIF;
    }

    /**
     * Generated from protobuf field <code>uint32 PDOMAMNJNIF = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPDOMAMNJNIF($var)
    {
        GPBUtil::checkUint32($var);
        $this->PDOMAMNJNIF = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 CBPBAHEADKJ = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCBPBAHEADKJ()
    {
        return $this->CBPBAHEADKJ;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 CBPBAHEADKJ = 13;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCBPBAHEADKJ($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->CBPBAHEADKJ = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IPDPIAGBMNO HAJAODDHKCN = 9;</code>
     * @return \IPDPIAGBMNO|null
     */
    public function getHAJAODDHKCN()
    {
        return $this->HAJAODDHKCN;
    }

    public function hasHAJAODDHKCN()
    {
        return isset($this->HAJAODDHKCN);
    }

    public function clearHAJAODDHKCN()
    {
        unset($this->HAJAODDHKCN);
    }

    /**
     * Generated from protobuf field <code>.IPDPIAGBMNO HAJAODDHKCN = 9;</code>
     * @param \IPDPIAGBMNO $var
     * @return $this
     */
    public function setHAJAODDHKCN($var)
    {
        GPBUtil::checkMessage($var, \IPDPIAGBMNO::class);
        $this->HAJAODDHKCN = $var;

        return $this;
    }

}

