<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * KFMBBBBHECO (4527)
 *
 * Generated from protobuf message <code>PlayerReturnPointChangeScNotify</code>
 */
class PlayerReturnPointChangeScNotify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 lbdmholpjke = 13;</code>
     */
    protected $lbdmholpjke = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $lbdmholpjke
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 lbdmholpjke = 13;</code>
     * @return int
     */
    public function getLbdmholpjke()
    {
        return $this->lbdmholpjke;
    }

    /**
     * Generated from protobuf field <code>uint32 lbdmholpjke = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setLbdmholpjke($var)
    {
        GPBUtil::checkUint32($var);
        $this->lbdmholpjke = $var;

        return $this;
    }

}

