<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POKBAPPHOPK</code>
 */
class POKBAPPHOPK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 12;</code>
     */
    private $base_avatar_id_list;
    /**
     * Generated from protobuf field <code>.JGALANANANF NEMGEOPCBAO = 13;</code>
     */
    protected $NEMGEOPCBAO = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $base_avatar_id_list
     *     @type \JGALANANANF $NEMGEOPCBAO
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBaseAvatarIdList()
    {
        return $this->base_avatar_id_list;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 base_avatar_id_list = 12;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBaseAvatarIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->base_avatar_id_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.JGALANANANF NEMGEOPCBAO = 13;</code>
     * @return \JGALANANANF|null
     */
    public function getNEMGEOPCBAO()
    {
        return $this->NEMGEOPCBAO;
    }

    public function hasNEMGEOPCBAO()
    {
        return isset($this->NEMGEOPCBAO);
    }

    public function clearNEMGEOPCBAO()
    {
        unset($this->NEMGEOPCBAO);
    }

    /**
     * Generated from protobuf field <code>.JGALANANANF NEMGEOPCBAO = 13;</code>
     * @param \JGALANANANF $var
     * @return $this
     */
    public function setNEMGEOPCBAO($var)
    {
        GPBUtil::checkMessage($var, \JGALANANANF::class);
        $this->NEMGEOPCBAO = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

