<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RelicList</code>
 */
class RelicList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 set_id = 15;</code>
     */
    protected $set_id = 0;
    /**
     * Generated from protobuf field <code>uint32 type = 8;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $set_id
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 set_id = 15;</code>
     * @return int
     */
    public function getSetId()
    {
        return $this->set_id;
    }

    /**
     * Generated from protobuf field <code>uint32 set_id = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setSetId($var)
    {
        GPBUtil::checkUint32($var);
        $this->set_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 8;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

}

