<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LONOLPHBNLA (5687)
 *
 * Generated from protobuf message <code>RogueGetGambleInfoScRsp</code>
 */
class RogueGetGambleInfoScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.BLKFPMIBJKO nofjpppaike = 1;</code>
     */
    protected $nofjpppaike = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \BLKFPMIBJKO $nofjpppaike
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.BLKFPMIBJKO nofjpppaike = 1;</code>
     * @return \BLKFPMIBJKO|null
     */
    public function getNofjpppaike()
    {
        return $this->nofjpppaike;
    }

    public function hasNofjpppaike()
    {
        return isset($this->nofjpppaike);
    }

    public function clearNofjpppaike()
    {
        unset($this->nofjpppaike);
    }

    /**
     * Generated from protobuf field <code>.BLKFPMIBJKO nofjpppaike = 1;</code>
     * @param \BLKFPMIBJKO $var
     * @return $this
     */
    public function setNofjpppaike($var)
    {
        GPBUtil::checkMessage($var, \BLKFPMIBJKO::class);
        $this->nofjpppaike = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

