<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SceneGroupEntityRefreshInfo</code>
 */
class SceneGroupEntityRefreshInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.SceneEntityInfo refresh_entity_info = 8;</code>
     */
    protected $refresh_entity_info = null;
    /**
     * KGLMIMBICIN
     *
     * Generated from protobuf field <code>uint32 delete_entity = 12;</code>
     */
    protected $delete_entity = 0;
    /**
     * Generated from protobuf field <code>uint32 melfhaojlel = 13;</code>
     */
    protected $melfhaojlel = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \SceneEntityInfo $refresh_entity_info
     *     @type int $delete_entity
     *           KGLMIMBICIN
     *     @type int $melfhaojlel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.SceneEntityInfo refresh_entity_info = 8;</code>
     * @return \SceneEntityInfo|null
     */
    public function getRefreshEntityInfo()
    {
        return $this->refresh_entity_info;
    }

    public function hasRefreshEntityInfo()
    {
        return isset($this->refresh_entity_info);
    }

    public function clearRefreshEntityInfo()
    {
        unset($this->refresh_entity_info);
    }

    /**
     * Generated from protobuf field <code>.SceneEntityInfo refresh_entity_info = 8;</code>
     * @param \SceneEntityInfo $var
     * @return $this
     */
    public function setRefreshEntityInfo($var)
    {
        GPBUtil::checkMessage($var, \SceneEntityInfo::class);
        $this->refresh_entity_info = $var;

        return $this;
    }

    /**
     * KGLMIMBICIN
     *
     * Generated from protobuf field <code>uint32 delete_entity = 12;</code>
     * @return int
     */
    public function getDeleteEntity()
    {
        return $this->delete_entity;
    }

    /**
     * KGLMIMBICIN
     *
     * Generated from protobuf field <code>uint32 delete_entity = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDeleteEntity($var)
    {
        GPBUtil::checkUint32($var);
        $this->delete_entity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 melfhaojlel = 13;</code>
     * @return int
     */
    public function getMelfhaojlel()
    {
        return $this->melfhaojlel;
    }

    /**
     * Generated from protobuf field <code>uint32 melfhaojlel = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setMelfhaojlel($var)
    {
        GPBUtil::checkUint32($var);
        $this->melfhaojlel = $var;

        return $this;
    }

}

