<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LKPAHMELFAH (7553)
 *
 * Generated from protobuf message <code>SettleTrackPhotoStageCsReq</code>
 */
class SettleTrackPhotoStageCsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .HLCCNEHFDBA kcnnkniaeka = 8;</code>
     */
    private $kcnnkniaeka;
    /**
     * Generated from protobuf field <code>uint32 cost_time = 14;</code>
     */
    protected $cost_time = 0;
    /**
     * Generated from protobuf field <code>uint32 stage_id = 3;</code>
     */
    protected $stage_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\HLCCNEHFDBA>|\Google\Protobuf\Internal\RepeatedField $kcnnkniaeka
     *     @type int $cost_time
     *     @type int $stage_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .HLCCNEHFDBA kcnnkniaeka = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKcnnkniaeka()
    {
        return $this->kcnnkniaeka;
    }

    /**
     * Generated from protobuf field <code>repeated .HLCCNEHFDBA kcnnkniaeka = 8;</code>
     * @param array<\HLCCNEHFDBA>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKcnnkniaeka($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \HLCCNEHFDBA::class);
        $this->kcnnkniaeka = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cost_time = 14;</code>
     * @return int
     */
    public function getCostTime()
    {
        return $this->cost_time;
    }

    /**
     * Generated from protobuf field <code>uint32 cost_time = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setCostTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 stage_id = 3;</code>
     * @return int
     */
    public function getStageId()
    {
        return $this->stage_id;
    }

    /**
     * Generated from protobuf field <code>uint32 stage_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStageId($var)
    {
        GPBUtil::checkUint32($var);
        $this->stage_id = $var;

        return $this;
    }

}

