<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StartChallengeInfo</code>
 */
class StartChallengeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.StartChallengeStoryBuffInfo story_buff_info = 3;</code>
     */
    protected $story_buff_info = null;
    /**
     * Generated from protobuf field <code>.StartChallengeBossBuffInfo boss_buff_info = 12;</code>
     */
    protected $boss_buff_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \StartChallengeStoryBuffInfo $story_buff_info
     *     @type \StartChallengeBossBuffInfo $boss_buff_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.StartChallengeStoryBuffInfo story_buff_info = 3;</code>
     * @return \StartChallengeStoryBuffInfo|null
     */
    public function getStoryBuffInfo()
    {
        return $this->story_buff_info;
    }

    public function hasStoryBuffInfo()
    {
        return isset($this->story_buff_info);
    }

    public function clearStoryBuffInfo()
    {
        unset($this->story_buff_info);
    }

    /**
     * Generated from protobuf field <code>.StartChallengeStoryBuffInfo story_buff_info = 3;</code>
     * @param \StartChallengeStoryBuffInfo $var
     * @return $this
     */
    public function setStoryBuffInfo($var)
    {
        GPBUtil::checkMessage($var, \StartChallengeStoryBuffInfo::class);
        $this->story_buff_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.StartChallengeBossBuffInfo boss_buff_info = 12;</code>
     * @return \StartChallengeBossBuffInfo|null
     */
    public function getBossBuffInfo()
    {
        return $this->boss_buff_info;
    }

    public function hasBossBuffInfo()
    {
        return isset($this->boss_buff_info);
    }

    public function clearBossBuffInfo()
    {
        unset($this->boss_buff_info);
    }

    /**
     * Generated from protobuf field <code>.StartChallengeBossBuffInfo boss_buff_info = 12;</code>
     * @param \StartChallengeBossBuffInfo $var
     * @return $this
     */
    public function setBossBuffInfo($var)
    {
        GPBUtil::checkMessage($var, \StartChallengeBossBuffInfo::class);
        $this->boss_buff_info = $var;

        return $this;
    }

}

