<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * HGBLDCADMGM (2607)
 *
 * Generated from protobuf message <code>SubmitMaterialSubmitActivityMaterialScRsp</code>
 */
class SubmitMaterialSubmitActivityMaterialScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     */
    protected $retcode = 0;
    /**
     * Generated from protobuf field <code>.JCOFDIPBJME cfdepejiggg = 9;</code>
     */
    protected $cfdepejiggg = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retcode
     *     @type \JCOFDIPBJME $cfdepejiggg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.JCOFDIPBJME cfdepejiggg = 9;</code>
     * @return \JCOFDIPBJME|null
     */
    public function getCfdepejiggg()
    {
        return $this->cfdepejiggg;
    }

    public function hasCfdepejiggg()
    {
        return isset($this->cfdepejiggg);
    }

    public function clearCfdepejiggg()
    {
        unset($this->cfdepejiggg);
    }

    /**
     * Generated from protobuf field <code>.JCOFDIPBJME cfdepejiggg = 9;</code>
     * @param \JCOFDIPBJME $var
     * @return $this
     */
    public function setCfdepejiggg($var)
    {
        GPBUtil::checkMessage($var, \JCOFDIPBJME::class);
        $this->cfdepejiggg = $var;

        return $this;
    }

}

