<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PHKEPDAKLNL (2507)
 *
 * Generated from protobuf message <code>TakeMultipleActivityExpeditionRewardCsReq</code>
 */
class TakeMultipleActivityExpeditionRewardCsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 jjnnkjhfakj = 5;</code>
     */
    private $jjnnkjhfakj;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $jjnnkjhfakj
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 jjnnkjhfakj = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJjnnkjhfakj()
    {
        return $this->jjnnkjhfakj;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 jjnnkjhfakj = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJjnnkjhfakj($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->jjnnkjhfakj = $arr;

        return $this;
    }

}

