<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * JNPMJEGDDNL (5611)
 *
 * Generated from protobuf message <code>TakeRogueEventHandbookRewardCsReq</code>
 */
class TakeRogueEventHandbookRewardCsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 accpehfpkab = 4;</code>
     */
    private $accpehfpkab;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $accpehfpkab
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 accpehfpkab = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAccpehfpkab()
    {
        return $this->accpehfpkab;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 accpehfpkab = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAccpehfpkab($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->accpehfpkab = $arr;

        return $this;
    }

}

