<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * FBGFCAGCDCJ (2627)
 *
 * Generated from protobuf message <code>TakeLoginActivityRewardScRsp</code>
 */
class TakeLoginActivityRewardScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ItemList reward = 15;</code>
     */
    protected $reward = null;
    /**
     * Generated from protobuf field <code>uint32 take_days = 1;</code>
     */
    protected $take_days = 0;
    /**
     * Generated from protobuf field <code>uint32 id = 9;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint32 panel_id = 4;</code>
     */
    protected $panel_id = 0;
    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ItemList $reward
     *     @type int $take_days
     *     @type int $id
     *     @type int $panel_id
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 15;</code>
     * @return \ItemList|null
     */
    public function getReward()
    {
        return $this->reward;
    }

    public function hasReward()
    {
        return isset($this->reward);
    }

    public function clearReward()
    {
        unset($this->reward);
    }

    /**
     * Generated from protobuf field <code>.ItemList reward = 15;</code>
     * @param \ItemList $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \ItemList::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 take_days = 1;</code>
     * @return int
     */
    public function getTakeDays()
    {
        return $this->take_days;
    }

    /**
     * Generated from protobuf field <code>uint32 take_days = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTakeDays($var)
    {
        GPBUtil::checkUint32($var);
        $this->take_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 9;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 panel_id = 4;</code>
     * @return int
     */
    public function getPanelId()
    {
        return $this->panel_id;
    }

    /**
     * Generated from protobuf field <code>uint32 panel_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPanelId($var)
    {
        GPBUtil::checkUint32($var);
        $this->panel_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

