<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * UnlockTutorialScRsp (1628)
 *
 * Generated from protobuf message <code>UnlockTutorialScRsp</code>
 */
class UnlockTutorialScRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Tutorial Tutorial = 4;</code>
     */
    protected $Tutorial = null;
    /**
     * Generated from protobuf field <code>uint32 retcode = 13;</code>
     */
    protected $retcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tutorial $Tutorial
     *     @type int $retcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Tutorial Tutorial = 4;</code>
     * @return \Tutorial|null
     */
    public function getTutorial()
    {
        return $this->Tutorial;
    }

    public function hasTutorial()
    {
        return isset($this->Tutorial);
    }

    public function clearTutorial()
    {
        unset($this->Tutorial);
    }

    /**
     * Generated from protobuf field <code>.Tutorial Tutorial = 4;</code>
     * @param \Tutorial $var
     * @return $this
     */
    public function setTutorial($var)
    {
        GPBUtil::checkMessage($var, \Tutorial::class);
        $this->Tutorial = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 13;</code>
     * @return int
     */
    public function getRetcode()
    {
        return $this->retcode;
    }

    /**
     * Generated from protobuf field <code>uint32 retcode = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setRetcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->retcode = $var;

        return $this;
    }

}

