<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DPBMAMHEHGG (6875)
 *
 * Generated from protobuf message <code>UpdateMapRotationDataScNotify</code>
 */
class UpdateMapRotationDataScNotify extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ifdgjojkbpn = 10;</code>
     */
    protected $ifdgjojkbpn = 0;
    /**
     * Generated from protobuf field <code>repeated .JJEJHCKMJLG dbmhdfodcdb = 7;</code>
     */
    private $dbmhdfodcdb;
    /**
     * Generated from protobuf field <code>.PJNIEDFALHN fpgmdipjkdj = 11;</code>
     */
    protected $fpgmdipjkdj = null;
    /**
     * Generated from protobuf field <code>bool goflefhokdf = 14;</code>
     */
    protected $goflefhokdf = false;
    /**
     * Generated from protobuf field <code>int32 fdggllhcpli = 4;</code>
     */
    protected $fdggllhcpli = 0;
    /**
     * Generated from protobuf field <code>.LAMKDPDMLEC kbmflpnpkoj = 13;</code>
     */
    protected $kbmflpnpkoj = null;
    /**
     * Generated from protobuf field <code>repeated .GFNOJBNEOAA jgfohpfekbe = 12;</code>
     */
    private $jgfohpfekbe;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ifdgjojkbpn
     *     @type array<\JJEJHCKMJLG>|\Google\Protobuf\Internal\RepeatedField $dbmhdfodcdb
     *     @type \PJNIEDFALHN $fpgmdipjkdj
     *     @type bool $goflefhokdf
     *     @type int $fdggllhcpli
     *     @type \LAMKDPDMLEC $kbmflpnpkoj
     *     @type array<\GFNOJBNEOAA>|\Google\Protobuf\Internal\RepeatedField $jgfohpfekbe
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ifdgjojkbpn = 10;</code>
     * @return int
     */
    public function getIfdgjojkbpn()
    {
        return $this->ifdgjojkbpn;
    }

    /**
     * Generated from protobuf field <code>uint32 ifdgjojkbpn = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setIfdgjojkbpn($var)
    {
        GPBUtil::checkUint32($var);
        $this->ifdgjojkbpn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .JJEJHCKMJLG dbmhdfodcdb = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDbmhdfodcdb()
    {
        return $this->dbmhdfodcdb;
    }

    /**
     * Generated from protobuf field <code>repeated .JJEJHCKMJLG dbmhdfodcdb = 7;</code>
     * @param array<\JJEJHCKMJLG>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDbmhdfodcdb($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \JJEJHCKMJLG::class);
        $this->dbmhdfodcdb = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PJNIEDFALHN fpgmdipjkdj = 11;</code>
     * @return \PJNIEDFALHN|null
     */
    public function getFpgmdipjkdj()
    {
        return $this->fpgmdipjkdj;
    }

    public function hasFpgmdipjkdj()
    {
        return isset($this->fpgmdipjkdj);
    }

    public function clearFpgmdipjkdj()
    {
        unset($this->fpgmdipjkdj);
    }

    /**
     * Generated from protobuf field <code>.PJNIEDFALHN fpgmdipjkdj = 11;</code>
     * @param \PJNIEDFALHN $var
     * @return $this
     */
    public function setFpgmdipjkdj($var)
    {
        GPBUtil::checkMessage($var, \PJNIEDFALHN::class);
        $this->fpgmdipjkdj = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool goflefhokdf = 14;</code>
     * @return bool
     */
    public function getGoflefhokdf()
    {
        return $this->goflefhokdf;
    }

    /**
     * Generated from protobuf field <code>bool goflefhokdf = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setGoflefhokdf($var)
    {
        GPBUtil::checkBool($var);
        $this->goflefhokdf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fdggllhcpli = 4;</code>
     * @return int
     */
    public function getFdggllhcpli()
    {
        return $this->fdggllhcpli;
    }

    /**
     * Generated from protobuf field <code>int32 fdggllhcpli = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFdggllhcpli($var)
    {
        GPBUtil::checkInt32($var);
        $this->fdggllhcpli = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LAMKDPDMLEC kbmflpnpkoj = 13;</code>
     * @return \LAMKDPDMLEC|null
     */
    public function getKbmflpnpkoj()
    {
        return $this->kbmflpnpkoj;
    }

    public function hasKbmflpnpkoj()
    {
        return isset($this->kbmflpnpkoj);
    }

    public function clearKbmflpnpkoj()
    {
        unset($this->kbmflpnpkoj);
    }

    /**
     * Generated from protobuf field <code>.LAMKDPDMLEC kbmflpnpkoj = 13;</code>
     * @param \LAMKDPDMLEC $var
     * @return $this
     */
    public function setKbmflpnpkoj($var)
    {
        GPBUtil::checkMessage($var, \LAMKDPDMLEC::class);
        $this->kbmflpnpkoj = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .GFNOJBNEOAA jgfohpfekbe = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJgfohpfekbe()
    {
        return $this->jgfohpfekbe;
    }

    /**
     * Generated from protobuf field <code>repeated .GFNOJBNEOAA jgfohpfekbe = 12;</code>
     * @param array<\GFNOJBNEOAA>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJgfohpfekbe($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GFNOJBNEOAA::class);
        $this->jgfohpfekbe = $arr;

        return $this;
    }

}

