<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StarRail.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoKeyInfo</code>
 */
class VideoKeyInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 8;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 video_key = 12;</code>
     */
    protected $video_key = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int|string $video_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StarRail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 8;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 video_key = 12;</code>
     * @return int|string
     */
    public function getVideoKey()
    {
        return $this->video_key;
    }

    /**
     * Generated from protobuf field <code>uint64 video_key = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVideoKey($var)
    {
        GPBUtil::checkUint64($var);
        $this->video_key = $var;

        return $this;
    }

}

